<?php
/**
 * Static contracts for Npcink OpenClaw Adapter.
 *
 * @package NpcinkOpenClawAdapter
 */

$root = dirname( __DIR__ );

/**
 * Assertion helper.
 *
 * @param bool   $condition Condition.
 * @param string $message Message.
 * @return void
 */
function maa_adapter_assert( bool $condition, string $message ): void {
	if ( ! $condition ) {
		fwrite( STDERR, '[fail] ' . $message . "\n" );
		exit( 1 );
	}
}

/**
 * Reads a file.
 *
 * @param string $path Path.
 * @return string
 */
function maa_adapter_read( string $path ): string {
	$contents = is_readable( $path ) ? file_get_contents( $path ) : false;
	return is_string( $contents ) ? $contents : '';
}

$main = maa_adapter_read( $root . '/npcink-openclaw-adapter.php' );
maa_adapter_assert( false !== strpos( $main, 'Plugin Name: Npcink OpenClaw Adapter' ), 'Main plugin has WordPress plugin header.' );
maa_adapter_assert( false !== strpos( $main, 'License: GPL-2.0-or-later' ), 'Main plugin declares GPL-compatible license.' );
maa_adapter_assert( false !== strpos( $main, 'plugins_loaded' ), 'Main plugin boots on plugins_loaded.' );

$controller = maa_adapter_read( $root . '/includes/Rest/Controller.php' );
foreach (
	array(
		'npcink-openclaw-adapter/v1',
		'/health',
		'/help',
		'/capabilities',
		'/connection/manifest',
		'/connect/device/start',
		'/connect/device/poll',
		'/connection/key-pairs',
		'connection_manifest',
		'start_device_pairing',
		'poll_device_pairing',
		'approve_device_pairing',
		'revoke_client_key_by_id',
		'authenticate_signed_request',
		'signed_request_credentials',
		'DEVICE_PAIRING_TTL',
		'SIGNATURE_NONCE_TTL',
		'key_pair_device_pairing',
		'npcink-key-pair-auth.v1',
		'x_npcink_key_id',
		'Npcink-Signature',
		'Ed25519',
		'/run-read-ability',
		'/media-metadata-optimization',
		'media_metadata_optimization_route',
		'npcink-abilities-toolkit/optimize-media-metadata',
		'/media-derivative-runs',
		'/media-derivative-runs/(?P<run_id>[A-Za-z0-9._:-]+)',
		'/media-derivative-runs/(?P<run_id>[A-Za-z0-9._:-]+)/result',
		'/media-derivative-artifacts/(?P<artifact_id>[A-Za-z0-9._:-]+)/preview',
		'/media-derivative-proposal-payload',
		'can_use_media_derivative_artifact_preview',
		'create_media_derivative_run',
		'get_media_derivative_run',
		'get_media_derivative_run_result',
		'download_media_derivative_artifact_preview',
		'build_media_derivative_proposal_payload',
		'npcink-abilities-toolkit/build-media-derivative-cloud-request',
		'npcink_cloud_addon_dispatch_media_derivative_cloud_request',
		'npcink_cloud_addon_verified_runtime_client',
		'npcink_cloud_addon_build_media_derivative_proposal_payload',
		'npcink_cloud_addon_download_media_derivative_artifact',
		'npcink_governance_core_build_media_derivative_ability_input',
		"'watermark_enabled'",
		"isset( \$overrides['preferred_format'] ) && ! isset( \$overrides['target_format'] )",
		"isset( \$overrides['target_max_width'] ) && ! isset( \$overrides['max_width'] )",
		"unset( \$ability_input['watermark'] )",
		'npcink_governance_core_get_media_derivative_settings',
		'media_derivative_adapter_run.v1',
		'media_derivative_cloud_request.v1',
		'media_derivative_adapter_run_status.v1',
		'media_derivative_adapter_run_result.v1',
		'media_derivative_adapter_proposal_payload.v1',
		'media_derivative_artifact_preview_url',
		'media_derivative_artifact_preview_signature',
		'valid_media_derivative_artifact_preview_signature',
		'media_derivative_preview_expires_at',
		'preview_url',
		'preview_sig',
		'expires_ts',
		'wp_salt( \'auth\' )',
		'X-Content-Type-Options: nosniff',
		'media_derivative_source_artifact',
		'media_derivative_watermark_artifact',
		"'text' === sanitize_key( (string) ( \$watermark['type'] ?? 'image' ) )",
		'attachment_upload_descriptor',
		'final_write_owner',
		'local_wordpress_host',
		'wordpress_write_included',
		'attachment_metadata_write_included',
		'core_proposal_required',
		'/ai-provider-log-correlation-smoke',
		'ai_provider_log_correlation_smoke',
		'observability_request_context',
		'safe_observability_context',
		'adapter.core.request',
		'adapter.proposal.create',
		'adapter.proposal.plan_ingest',
		'adapter.commit.preflight',
		'adapter.proposal.execute',
		'status_code',
		'/site-info',
		'/site-summary',
			'/wp-diagnostics-summary',
			'/wp-ops-diagnostics-detail',
			'active-plugins-detail',
			'plugin-conflict-diagnostics',
			'current-user-permissions',
			'php-extensions',
			'object-cache-status',
			'rewrite-rules-status',
			'ssl-https-status',
			'recent-error-log',
			'recent-error-log-tail',
			'database-info',
			'cron-events-detail',
			'custom-post-types',
			'roles-capabilities',
			'widgets-sidebars',
			'block-theme-assets',
			'search-index-status',
			'server-info',
			'integrations-status',
			'seo-summary',
			'security-summary',
			'performance-summary',
			'read_shortcut_definitions',
			'ops_diagnostics_input',
			'ops_diagnostics_plugin_conflict_input',
			'ops_diagnostics_log_input',
			'include_log_contents',
			'include_active_plugins',
			'include_inactive_plugins',
			'include_plugin_updates',
			'include_must_use_plugins',
			'include_dropins',
			'max_plugins_per_group',
			'tail_lines',
			'since_minutes',
			'not explicitly requested',
			'inactive plugin rows are not requested by default',
			'route_groups',
			'help_route_groups',
			'help_routes_flat',
			'help_route_purpose',
			'GET /term?id={id}',
			'normalize_shortcut_input',
			'boolean_input_value',
			'include_delete_candidates',
			'include_trash_parent_media',
			'include_unattached_test_media',
			'allowed_plan_ability_ids',
			'npcink_openclaw_adapter_plan_ability_not_allowed',
			'execution_profiles',
			'validate_proposal_create_input',
			'validate_plan_write_action_inputs',
			'invalid_output_reference_token',
			'allowed_execute_ability_ids',
			'allowed_input_fields',
			'enum_fields',
			'npcink_openclaw_adapter_ability_input_field_not_allowed',
			'source_type',
			'npcink_openclaw_adapter_media_source_type_invalid',
			'owned',
			'ai_generated',
			'stock',
			'external',
			'test',
			'npcink_openclaw_adapter_plan_action_input_invalid',
			'validate_output_references',
			'resolve_output_references',
			'npcink_openclaw_adapter_output_reference_unavailable',
			'npcink_openclaw_adapter_output_reference_unresolved',
			'post_id_from_result',
			'force_post_input',
			'required_slug_fields',
			'validate_terms_input',
			'validate_delete_term_input',
			'execute_approved_proposal_route',
			'approve_and_execute_proposal_route',
			'/execute-approved-proposal',
			'/proposals/(?P<proposal_id>[A-Za-z0-9_-]+)/execute',
			'/proposals/(?P<proposal_id>[A-Za-z0-9_-]+)/approve-and-execute',
			'approved_proposal_execution_routes',
			'approved_proposal_execution',
			'unified_approve_and_execute',
			'core_approval_then_adapter_execution',
			'npcink_openclaw_adapter_unified_action',
			'core_approved_commit_preflight_required',
			'wp_abilities_rest_after_core_preflight',
			'MAX_EXECUTION_ACTIONS',
			'execution_input_contract',
			'partial_success',
			'batch_write_actions',
			'normalize_execution_actions',
			'execute_normalized_action',
			'npcink_openclaw_adapter_execute_ability_not_allowed',
			'npcink_openclaw_adapter_execution_input_ambiguous',
			'npcink_openclaw_adapter_write_action_invalid',
			'npcink_openclaw_adapter_write_action_target_required',
			'npcink_openclaw_adapter_write_actions_limit_exceeded',
			'npcink_openclaw_adapter_write_action_commit_execution_not_allowed',
			'npcink_openclaw_adapter_preflight_not_authorized',
			'npcink_openclaw_adapter_core_execution_not_allowed',
			'npcink_openclaw_adapter_proposal_rejected',
			'npcink_openclaw_adapter_preflight_item_blocked',
			'operator_feedback',
			'error_with_operator_feedback',
			'plan_handoff_operator_feedback',
			'proposal_status_operator_feedback',
			'preflight_operator_feedback',
			'can_retry_after_revision',
			'core_evidence',
			'npcink_openclaw_adapter_preflight_correlation_required',
			'execute_core_approved_proposal',
			'EXECUTION_RECORDS_OPTION',
			'PREFLIGHT_HANDOFFS_OPTION',
			'MAX_PREFLIGHT_HANDOFFS',
			'preflight_handoffs',
			'store_preflight_handoff',
			'consume_cached_preflight_handoff',
			'prune_preflight_handoffs',
			'validate_preflight_binding',
			'proposal_input_hash',
			'npcink_openclaw_adapter_preflight_input_hash_mismatch',
			'npcink_openclaw_adapter_preflight_policy_version_invalid',
			'core-preflight-v1',
			'approved_input_hash',
			'policy_version',
			'adapter_preflight_handoff_cached',
			'adapter_preflight_source',
			'npcink_governance_core_commit_preflight_already_issued',
			'completed_execution_record',
			'store_completed_execution_record',
			'store_failed_execution_record',
			'failed_action_id',
			'failed_action_index',
			'npcink_openclaw_adapter_execution_already_completed',
			'execution_record',
			'get_core_proposal_data',
			'validate_execute_ability',
			'dispatch_upstream_with_runtime_context',
			'npcink_ai_runtime_wp_ability_context',
			'sanitize_runtime_context',
			'approval_commit_authorized',
			'approval_context',
			'proposal_caller_context',
			"'term_id'",
			'plugin_conflict_input',
			'plugin_group_fields',
			'error_log_summary_fields',
		'workflow-recipes',
		'/workflow-recipe',
		'openclaw_recipes',
		'article_draft_plan',
		'article_media_batch_plan',
		'content_discoverability_suggestions',
		'ai_article_draft_with_discoverability',
		'media_derivative_cloud',
		'Media derivative Cloud artifact',
		"'content-discoverability-context'",
		"'content-discoverability-validation'",
		"'content-discoverability-brief'",
		"'article-writing-pack'",
		'npcink-toolbox/get-content-discoverability-context',
		'npcink-toolbox/validate-content-discoverability-context',
		'npcink-toolbox/build-content-discoverability-brief',
		'npcink-toolbox/build-ai-article-writing-pack',
		'content_discoverability_brief',
		'ai_article_writing_pack',
		'suggestion_only',
		"'media'",
		"'posts'",
		"'post-context'",
		"'users'",
		"'menu'",
		"'pages'",
		"'site-operations-dashboard'",
		'/proposals',
		'/proposals/from-plan',
		'create_proposals_from_plan',
		'list_proposals',
		'get_proposal',
		'approval_proxy_disabled',
		'/proposals/(?P<proposal_id>[A-Za-z0-9_-]+)/approve',
		'/proposals/(?P<proposal_id>[A-Za-z0-9_-]+)/reject',
		'/commit-preflight',
		"current_user_can( 'manage_options' )",
		'/npcink-governance-core/v1/capabilities',
		'/npcink-governance-core/v1/proposals',
		"caller_type' => 'openclaw_adapter'",
		"'via'         => 'npcink-openclaw-adapter'",
		'/wp-abilities/v1/abilities/',
		'governance_mode',
		'direct_read',
		'read_policy',
		'direct_read_public',
		'direct_read_internal',
		'direct_read_sensitive',
		'sensitivity',
		'redaction_required',
		'redaction_applied',
		'redaction_summary',
		'read_governance_context',
		'apply_read_redaction',
		'is_sensitive_read_key',
		'read_context',
		'proposal_required',
		'wp_abilities_rest',
		'adapter_after_core_preflight',
		'direct_read_plan_to_core_proposals',
		'plan_to_proposal',
		'core_proxy_execute',
		'commit_execution',
		'plan_fields_preserved',
		'batch_id',
		'issue_types',
		'attachment_ids',
		'post_ids',
		'write_actions',
		'manual_review',
		'skipped_destructive_candidates',
		'issue_counts',
		'action_count',
		'adapter_base_url',
		'help_url',
		'proposal_list_url',
		'proposal_detail_url',
		'read_shortcuts',
		'wordpress_rest_application_password',
		'proposal_status',
		'proposals:read',
		'approval_proxy_enabled',
		'approval_surface',
		'npcink_governance_core_admin',
		'log_context',
		'wpai_request_log_context',
		'append_ai_request_log_context',
		'with_ai_request_log_context',
		'ai_request_log_context',
		'proposal_id',
		'correlation_id',
		'adapter_request_id',
		'adapter_route',
		'ai_provider',
		'ai_model',
		'governance_source',
		'npcink_governance_core',
		'wp_ai_client_prompt',
		'qwen3.5:0.8b',
		'POST /ai-provider-log-correlation-smoke',
		'npcink_openclaw_adapter',
		'proposal_status_routes',
		'plan_proposal_routes',
		'core_app_token_configured',
		'core_app_token_required_scopes',
		'GET /proposals',
		'GET /proposals/{proposal_id}',
			'POST /proposals/{proposal_id}/approve',
			'POST /proposals/{proposal_id}/reject',
			'npcink_openclaw_adapter_approval_proxy_disabled',
			'unified_action_route',
			'approve-and-execute',
			'NPCINK_OPENCLAW_ADAPTER_CORE_APP_TOKEN',
		'npcink_openclaw_adapter_core_app_token',
		'x-npcink-governance-core-app-token',
		'npcink_openclaw_adapter_proposal_required',
		'npcink-abilities-toolkit/site-info',
			'npcink-abilities-toolkit/site-summary',
			'npcink-abilities-toolkit/wp-diagnostics-summary',
			'npcink-abilities-toolkit/wp-ops-diagnostics-detail',
			'npcink-abilities-toolkit/list-workflow-recipes',
		'npcink-abilities-toolkit/get-workflow-recipe',
		'npcink-abilities-toolkit/list-posts',
		'npcink-abilities-toolkit/get-post-context',
		'npcink-abilities-toolkit/list-media',
		'npcink-abilities-toolkit/resolve-media-attachment-by-url',
		'npcink-abilities-toolkit/list-users',
		'npcink-abilities-toolkit/get-menu',
		'npcink-abilities-toolkit/list-pages',
		'npcink-abilities-toolkit/get-site-operations-dashboard',
		'npcink-abilities-toolkit/build-content-inventory-fix-plan',
		'npcink-abilities-toolkit/build-test-content-cleanup-plan',
			'npcink-abilities-toolkit/build-media-inventory-fix-plan',
			'npcink-abilities-toolkit/build-media-reference-repair-plan',
			'npcink-abilities-toolkit/build-media-settings-reference-repair-plan',
			'npcink-abilities-toolkit/build-media-optimization-plan',
			'npcink-abilities-toolkit/build-media-rename-plan',
			'npcink-toolbox/build-article-write-plan',
			'npcink-toolbox/build-article-batch-write-plan',
			'npcink-toolbox/build-article-media-batch-write-plan',
			'npcink-toolbox/build-image-candidate-adoption-plan',
			'article_batch_draft_plan',
			'image_candidate_adoption_plan',
			'docs/openclaw-article-batch-draft-plan-recipe.md',
			'docs/openclaw-image-candidate-adoption-plan-recipe.md',
			'npcink-toolbox/build-content-discoverability-brief',
		'npcink-abilities-toolkit/upload-media-from-url',
		'npcink-abilities-toolkit/set-post-featured-image',
		'npcink-abilities-toolkit/inspect-media-asset',
		'npcink-abilities-toolkit/optimize-media-asset',
		'npcink-abilities-toolkit/replace-media-file',
		'npcink-abilities-toolkit/adopt-cloud-media-derivative',
		'npcink-abilities-toolkit/rename-media-file',
		'npcink-abilities-toolkit/patch-post-content',
		'npcink-abilities-toolkit/patch-setting-value',
		'npcink_openclaw_adapter_patch_operations_required',
		'patch-post-content execution input must include operations.',
		'patch-setting-value execution input must include operations.',
		'npcink_openclaw_adapter_setting_target_type_invalid',
		'patch-setting-value target_type must be option or theme_mod.',
			'npcink_openclaw_adapter_derivative_artifact_required',
			'derivative_artifact',
			"'url', 'title', 'file_name'",
			"'expected_derivative_mime_type', 'file_name', 'backup_suffix'",
			'media_details_input',
			'from_plan_request',
			'media_optimization_plan',
			'preferred_core_route',
			'legacy_derivative_proposal_payload_available',
			'ability_guard',
			'missing_capability_behavior',
			'surface_plan_ability_unavailable_do_not_split_into_two_proposals',
			'default_user_intent',
			'optimize_this_media_item',
			'required_reviewed_input',
			'request_reviewed_media_details_input_before_core_proposal',
			'single_approval_required',
			'do_not_split_user_intent',
			'adopt-cloud-media-derivative execution input must include derivative_artifact evidence.',
			'rename-media-file execution input must include target_file_name.',
			'rename-media-file conflict_mode must be fail or unique.',
			'rename-media-file execution input must target an existing attachment.',
			'expected_current_md5',
			'expected_current_sha256',
			'target_file_name',
			'npcink_openclaw_adapter_target_file_name_required',
			'upload-media-from-url execution input must include url.',
			'set-post-featured-image execution input must include post_id.',
			'set-post-featured-image execution input must include attachment_id or media_url.',
		'npcink_openclaw_adapter_media_replace_mode_invalid',
		'derivative_relative_file',
		'replacement_id',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $controller, $required ), 'Controller contains required text: ' . $required );
}
maa_adapter_assert( false === strpos( $controller, '$allowed_execute_ability_ids' ), 'Controller derives execute allowlist from execution profiles.' );
maa_adapter_assert( false === strpos( $controller, 'include_log_tail' ), 'Adapter does not implement old include_log_tail compatibility.' );
maa_adapter_assert( false === strpos( $controller, 'include_error_log' ), 'Adapter does not use old include_error_log diagnostics input.' );
maa_adapter_assert( false === strpos( $controller, 'can_approve_proposals' ), 'Adapter does not call Core proposal approval permission path.' );
maa_adapter_assert( false === strpos( $controller, 'can_reject_proposals' ), 'Adapter does not call Core proposal rejection permission path.' );
maa_adapter_assert( false === strpos( $controller, 'approve_proposal' ), 'Adapter does not call Core proposal approval callback.' );
maa_adapter_assert( false === strpos( $controller, 'reject_proposal' ), 'Adapter does not call Core proposal rejection callback.' );
maa_adapter_assert( false === strpos( $controller, 'proposals:approve' ), 'Adapter does not request proposal approval scope.' );
maa_adapter_assert( false === strpos( $controller, 'proposals:reject' ), 'Adapter does not request proposal rejection scope.' );
maa_adapter_assert( false === strpos( $controller, "'replace_original'" ), 'Adapter optimize-media-asset profile does not allow original replacement.' );
maa_adapter_assert( false === strpos( $controller, "'replacement_url'" ), 'Adapter replace-media-file profile does not allow external replacement URLs.' );
$safe_observability = substr( $controller, (int) strpos( $controller, 'private function safe_observability_context' ) );
foreach ( array( "'input'", "'plan'", "'preview'", "'response'", "'upstream_data'", "'authorization'", "'token'", "'secret'", "'prompt'", "'content'" ) as $forbidden ) {
	maa_adapter_assert( false === strpos( $safe_observability, $forbidden ), 'Safe observability context excludes raw field: ' . $forbidden );
}
$observability = maa_adapter_read( $root . '/includes/Observability.php' );
foreach ( array( 'sanitize_payload', "'event_id'", "'adapter_request_id'", "'status_code'", "'executed_count'", "'failed_count'" ) as $required ) {
	maa_adapter_assert( false !== strpos( $observability, $required ), 'Observability bridge keeps allowlisted field: ' . $required );
}
foreach ( array( "'input'", "'plan'", "'preview'", "'response'", "'upstream_data'", "'authorization'", "'token'", "'secret'", "'prompt'", "'content'" ) as $forbidden ) {
	maa_adapter_assert( false === strpos( $observability, $forbidden ), 'Observability bridge excludes raw field: ' . $forbidden );
}

$plugin = maa_adapter_read( $root . '/includes/Plugin.php' );
foreach (
	array(
		'rest_request_before_callbacks',
		'rest_request_after_callbacks',
		'capture_adapter_dispatch_start',
		'emit_adapter_dispatch_event',
		'adapter.openclaw.dispatch.completed',
		'adapter.openclaw.dispatch.failed',
		'adapter.dispatch_failed',
		'admin_menu',
		'admin_post_npcink_openclaw_adapter_create_openclaw_password',
		'register_admin_page',
		'handle_create_openclaw_password',
		'Admin\\Connection_Page',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $plugin, $required ), 'Plugin registers admin page text: ' . $required );
}

$connection_page = maa_adapter_read( $root . '/includes/Admin/Connection_Page.php' );
foreach (
	array(
		'Npcink OpenClaw Adapter',
		'Adapter',
		'OpenClaw Handoff Created',
		'Simple connection',
		'Higher security: signed key-pair',
		'Create Application Password connection',
		'add_submenu_page',
		'PARENT_MENU_SLUG',
		'WP_Application_Passwords::create_new_application_password',
		'Include LocalWP TLS setting',
		'LocalWP TLS option',
		'Use only for localhost or .local testing',
		'Connection values',
		'Copy manifest URL',
		'Proposal lookup',
		'Advanced',
		'Diagnostics, route catalog, examples, and boundary notes.',
		'maa-advanced-group',
		'adapter_proposal_id',
		'proposal_lookup',
		'render_proposal_lookup_result',
		'Open in Core',
		'Copy status URL',
		'Copy execute URL',
		'proposal_next_step_text',
		"DATETIME_DISPLAY_FORMAT = 'Y-m-d H:i:s'",
		'display_datetime',
		'wp_date( self::DATETIME_DISPLAY_FORMAT, $timestamp )',
		'$this->display_datetime( $created )',
		'$this->display_datetime( $updated )',
		"\$this->display_datetime( (string) ( \$record['last_used_at'] ?? '' ) )",
		'Adapter Base URL',
		'WordPress user',
		'Copy env placeholder',
		'Connection manifest',
		'content_discoverability_suggestions',
		'ai_article_draft_with_discoverability',
		'content-discoverability-validation',
		'content-discoverability-context',
		'content-discoverability-brief',
		'article-writing-pack',
			'Return suggestions only; do not write SEO meta',
			'primary entrypoint is content-discoverability-brief',
			'Use article-writing-pack only for broad article requests',
		'openclaw_connection_manifest_text',
		'WorkBuddy setup',
		'Copy WorkBuddy setup',
		'workbuddy_handoff_text',
		'Npcink OpenClaw Adapter WorkBuddy connection',
		'wordpress_application_password',
		'connection_id',
		'local-wordpress',
		'wordpress_application_password',
		'password_uuid',
		'Secret must be stored through OpenClaw credential store or dedicated secret field',
		'Diagnostics URLs',
		'Route catalog',
		'details class="maa-section"',
		'Proposal list',
		'Proposal detail',
		'Plan to proposals',
		'Commit preflight',
		'Approve and execute',
		'Approval disabled stub',
		'Reject disabled stub',
		'Example requests',
		'Handoff prompt',
		'Boundary',
		'NPCINK_OPENCLAW_ADAPTER_APPLICATION_PASSWORD',
		'NPCINK_OPENCLAW_ADAPTER_APPLICATION_PASSWORD=<store-in-openclaw-secret-vault>',
		'Copy this Application Password now.',
		'Paste it only into OpenClaw dedicated secret field',
		'GET /help',
		'GET /proposals/{proposal_id}',
		'approval_proxy_enabled=false',
		'approve-and-execute',
		'Current execution allowlist: npcink-abilities-toolkit/trash-post, npcink-abilities-toolkit/create-draft, npcink-abilities-toolkit/update-post, npcink-abilities-toolkit/patch-post-content, npcink-abilities-toolkit/patch-setting-value, npcink-abilities-toolkit/set-post-seo-meta, npcink-abilities-toolkit/set-post-slug, npcink-abilities-toolkit/set-post-terms, npcink-abilities-toolkit/delete-term, npcink-abilities-toolkit/update-media-details, npcink-abilities-toolkit/upload-media-from-url, npcink-abilities-toolkit/set-post-featured-image, npcink-abilities-toolkit/optimize-media-asset, npcink-abilities-toolkit/replace-media-file, npcink-abilities-toolkit/adopt-cloud-media-derivative, npcink-abilities-toolkit/rename-media-file, npcink-abilities-toolkit/delete-media-permanently, npcink-abilities-toolkit/reply-comment, npcink-abilities-toolkit/trash-comment, npcink-abilities-toolkit/approve-comment',
		'Adapter execute routes are final write paths and normalize ability input to dry_run=false and commit=true',
		'for dry-run-only verification, stop at commit-preflight and do not call execute',
		'Failure code handling',
		'npcink_openclaw_adapter_preflight_item_blocked',
		'AI Request Logs context',
		'wpai_request_log_context',
		'log_context',
		'proposal_id',
		'correlation_id',
		'core_proxy_execute=false',
		'commit_execution=false',
		'<openclaw-secret-field-value>',
		'Key pair clients',
		'Device-paired clients',
		'Copy connect command',
		'Copy OpenClaw CLI instructions',
		'Copy status command',
		'local_cli_setup_text',
		'render_key_pair_clients_table',
		'local_cli_connect_command',
		'local_cli_status_command',
		'cd ~ && npm exec --yes --package @npcink/openclaw-adapter-cli@0.1.0 -- npcink-openclaw-adapter',
		'--intent=preflight',
		'--intent=commit',
		'final execute routes require --intent=commit',
		'Do not read, cat, print, summarize, or copy the local keypair profile file',
		'key_pairs_url',
		'REVOKE_KEY_ACTION',
		'Connection approved.',
		'Return to the terminal or local AI client',
		'private key was never sent to WordPress',
		'Connection rejected.',
		'PAIR_MENU_SLUG',
		'result_status',
		'/connection/manifest',
		'/connection/key-pairs',
		'Controller::read_shortcuts',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $connection_page, $required ), 'Connection page contains required text: ' . $required );
}
$env_password_key       = 'NPCINK_OPENCLAW_ADAPTER_APPLICATION_PASSWORD=';
$php_password_variable  = '$password';
maa_adapter_assert( false === strpos( $connection_page, $env_password_key . "' . " . $php_password_variable ), 'Connection page env text does not interpolate the real secret.' );
maa_adapter_assert( false === strpos( $connection_page, '$this->openclaw_env_text( $username, $password,' ), 'Connection page does not pass the real Application Password into env text.' );
maa_adapter_assert( false === strpos( $connection_page, '$this->openclaw_created_handoff_text( $username, $password,' ), 'Connection page does not pass the real secret into copied handoff.' );
maa_adapter_assert( false === strpos( $connection_page, '$this->workbuddy_handoff_text( $username, $password,' ), 'Connection page does not pass the real secret into WorkBuddy setup.' );
maa_adapter_assert( false === strpos( $connection_page, "echo esc_html( '' !== \$created ? \$created" ), 'Connection page does not output raw Core proposal creation time.' );
maa_adapter_assert( false === strpos( $connection_page, "echo esc_html( '' !== \$updated ? \$updated" ), 'Connection page does not output raw Core proposal update time.' );
maa_adapter_assert( false === strpos( $connection_page, "echo esc_html( (string) ( \$record['last_used_at'] ?? '' )" ), 'Connection page does not output raw key-pair last-used time.' );
maa_adapter_assert( false !== strpos( $connection_page, 'openclaw_connection_manifest_text( string $username, string $password_uuid )' ), 'Connection manifest receives only username and password UUID.' );
maa_adapter_assert( false !== strpos( $connection_page, 'openclaw_created_handoff_text( string $username, string $password_uuid, bool $include_local_tls )' ), 'Created handoff text receives only username, password UUID, and TLS placeholder flag.' );
maa_adapter_assert( false !== strpos( $connection_page, 'workbuddy_handoff_text( string $username, string $password_uuid, bool $include_local_tls )' ), 'WorkBuddy setup text receives only username, password UUID, and TLS placeholder flag.' );
maa_adapter_assert( false !== strpos( $connection_page, "const MENU_SLUG        = 'npcink-openclaw-adapter';" ), 'Connection page uses the canonical Adapter admin slug.' );
maa_adapter_assert( false !== strpos( $connection_page, "__( 'Npcink OpenClaw Adapter', 'npcink-openclaw-adapter' ),\n\t\t\t__( 'Adapter', 'npcink-openclaw-adapter' )," ), 'Connection page registers the requested page and menu titles.' );
maa_adapter_assert( false === strpos( $connection_page, 'npcink-openclaw-adapter-openclaw' ), 'Connection page does not use the old OpenClaw-specific admin slug.' );
maa_adapter_assert( false !== strpos( $connection_page, "'npcink-cloud-addon'" ), 'Connection page overview links to the canonical Cloud Addon slug.' );
maa_adapter_assert( false !== strpos( $connection_page, "__( 'Cloud Addon', 'npcink-openclaw-adapter' )" ), 'Connection page overview labels the Cloud Addon surface.' );

$admin_surface_standard = maa_adapter_read( $root . '/docs/admin-surface-standard.md' );
foreach (
	array(
		'OpenClaw connection surface',
		'Simple connection',
		'Higher security: signed key-pair',
		'Proposal ID status lookup',
		'duplicate Core review queue',
		'read shortcut route catalog',
		'Core proposal approval tables',
		'ability definitions',
		'Cloud Base URL/API key',
		'Time Display',
		'WordPress site timezone',
		'Y-m-d H:i:s',
		'Do not print raw UTC strings',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $admin_surface_standard, $required ), 'Admin surface standard documents Adapter page boundary: ' . $required );
}

$cloud_boundary = maa_adapter_read( $root . '/docs/cloud-connector-boundary.md' );
foreach (
	array(
		'Adapter is not the WordPress-to-Cloud connector',
		'Cloud Addon is the WordPress-side Cloud connector',
		'npcink_cloud_addon_runtime_client()',
		'npcink_cloud_addon_verified_runtime_client()',
		'Adapter must not expose a parallel `/cloud/*` REST surface',
		'Adapter-owned Cloud settings, signing clients, or `/cloud/*` routes',
		'Adapter does not register `/cloud/*` routes',
		'Adapter does not store Cloud API keys or sign Cloud requests',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $cloud_boundary, $required ), 'Cloud boundary keeps Adapter behind Cloud Addon: ' . $required );
}
foreach ( array( '/cloud/health', '/cloud/runs', '/cloud/analysis', '/cloud/stats' ) as $forbidden ) {
	maa_adapter_assert( false === strpos( $controller, $forbidden ), 'Controller does not register Adapter Cloud route: ' . $forbidden );
}
maa_adapter_assert( false === strpos( $controller, 'X-Npcink-Signature' ), 'Adapter controller does not implement Cloud request signing.' );
maa_adapter_assert( false === strpos( $cloud_boundary, 'Adapter is the WordPress-to-Cloud connector.' ), 'Cloud boundary no longer assigns Cloud connector ownership to Adapter.' );

$readme = maa_adapter_read( $root . '/README.md' );
foreach (
	array(
		'thin OpenClaw channel plugin',
		'read Npcink Governance Core capability guidance',
		'run approved direct-read abilities through WordPress Abilities API',
		'create Core proposals',
		'Cloud runtime access belongs to the standalone `npcink-cloud-addon`',
		'Adapter must not add its own Cloud settings, signing client, or `/cloud/*`',
		'POST /wp-json/npcink-openclaw-adapter/v1/media-derivative-runs',
		'GET /wp-json/npcink-openclaw-adapter/v1/media-derivative-runs/{run_id}',
		'GET /wp-json/npcink-openclaw-adapter/v1/media-derivative-runs/{run_id}/result',
		'GET /wp-json/npcink-openclaw-adapter/v1/media-derivative-artifacts/{artifact_id}/preview',
		'POST /wp-json/npcink-openclaw-adapter/v1/media-derivative-proposal-payload',
		'docs/openclaw-media-derivative-cloud-recipe.md',
		'Adapter emits local metadata-only events through',
		'npcink_openclaw_adapter_observability_event',
		'canonical Adapter event kinds are',
		'adapter.openclaw.dispatch.completed',
		'adapter.openclaw.dispatch.failed',
		'They must not include raw OpenClaw requests',
		'Proposal status',
		'Adapter status/execution URLs',
		'does not define abilities',
		'execute final write mutations',
		'Npcink -> Adapter',
		'docs/openclaw-quickstart.md',
		'docs/openclaw-connection-model-notes.md',
		'docs/openclaw-consumer-acceptance.md',
		'docs/openclaw-batch-execution-policy.md',
		'input.write_actions[]',
		'execution profile registry',
		'Capability discovery may show more proposal-required abilities',
		'$outputs.create-draft.post_id',
		'only its hash',
			'Application Password secret-field',
			'non-secret connection manifest',
			'copyable WorkBuddy setup block',
			'key-pair device pairing MVP',
			'docs/keypair-device-pairing-contract.md',
			'does not keep root-level `tools/` compatibility',
			'@npcink/openclaw-adapter-cli',
			'Final Adapter write routes',
			'--intent=preflight',
			'--intent=commit',
			'dry_run=true',
			'commit=false',
			'commit_execution=false',
			'Public Key Device Pairing',
			'OpenClaw only connects to Adapter',
			'productized OpenClaw user action',
			'GET /wp-json/npcink-openclaw-adapter/v1/help',
		'POST /wp-json/npcink-openclaw-adapter/v1/ai-provider-log-correlation-smoke',
			'GET /wp-json/npcink-openclaw-adapter/v1/site-summary',
			'GET /wp-json/npcink-openclaw-adapter/v1/active-plugins-detail',
			'GET /wp-json/npcink-openclaw-adapter/v1/plugin-conflict-diagnostics',
			'GET /wp-json/npcink-openclaw-adapter/v1/recent-error-log',
			'GET /wp-json/npcink-openclaw-adapter/v1/recent-error-log-tail',
			'GET /wp-json/npcink-openclaw-adapter/v1/current-user-permissions',
			'GET /wp-json/npcink-openclaw-adapter/v1/php-extensions',
			'GET /wp-json/npcink-openclaw-adapter/v1/object-cache-status',
			'GET /wp-json/npcink-openclaw-adapter/v1/database-info',
			'GET /wp-json/npcink-openclaw-adapter/v1/rewrite-rules-status',
			'GET /wp-json/npcink-openclaw-adapter/v1/cron-events-detail',
			'GET /wp-json/npcink-openclaw-adapter/v1/server-info',
			'GET /wp-json/npcink-openclaw-adapter/v1/integrations-status',
			'GET /wp-json/npcink-openclaw-adapter/v1/seo-summary',
			'GET /wp-json/npcink-openclaw-adapter/v1/security-summary',
			'GET /wp-json/npcink-openclaw-adapter/v1/performance-summary',
			'GET /wp-json/npcink-openclaw-adapter/v1/posts',
			'GET /wp-json/npcink-openclaw-adapter/v1/post-context',
			'GET /wp-json/npcink-openclaw-adapter/v1/users',
			'GET /wp-json/npcink-openclaw-adapter/v1/menu',
			'GET /wp-json/npcink-openclaw-adapter/v1/media',
			'GET /wp-json/npcink-openclaw-adapter/v1/article-writing-pack',
			'include_log_contents',
			'include_inactive_plugins',
			'max_plugins_per_group',
			'tail_lines',
			'since_minutes',
			'not explicitly requested',
			'error_log.tail_entries',
			'error_log.summary',
			'fatal_count',
			'deprecated_count',
			'summary_source',
			'error_log.summary.by_severity',
		'GET /wp-json/npcink-openclaw-adapter/v1/site-operations-dashboard',
		'GET /wp-json/npcink-openclaw-adapter/v1/proposals',
		'GET /wp-json/npcink-openclaw-adapter/v1/proposals/{proposal_id}',
		'POST /wp-json/npcink-openclaw-adapter/v1/proposals/from-plan',
		'POST /wp-json/npcink-openclaw-adapter/v1/execute-approved-proposal',
		'POST /wp-json/npcink-openclaw-adapter/v1/proposals/{proposal_id}/execute',
		'POST /wp-json/npcink-openclaw-adapter/v1/proposals/{proposal_id}/approve-and-execute',
		'POST /wp-json/npcink-openclaw-adapter/v1/proposals/{proposal_id}/approve',
		'POST /wp-json/npcink-openclaw-adapter/v1/proposals/{proposal_id}/reject',
		'approved proposal execution',
		'approve-and-execute',
		'npcink-abilities-toolkit/trash-post',
		'npcink-abilities-toolkit/create-draft',
		'npcink-abilities-toolkit/update-post',
		'npcink-abilities-toolkit/patch-post-content',
		'npcink-abilities-toolkit/patch-setting-value',
		'npcink-abilities-toolkit/set-post-seo-meta',
		'npcink-abilities-toolkit/set-post-slug',
		'npcink-abilities-toolkit/set-post-terms',
		'npcink-abilities-toolkit/delete-term',
		'npcink-abilities-toolkit/update-media-details',
		'npcink-abilities-toolkit/optimize-media-asset',
		'npcink-abilities-toolkit/replace-media-file',
		'npcink-abilities-toolkit/adopt-cloud-media-derivative',
		'npcink-abilities-toolkit/rename-media-file',
		'npcink-abilities-toolkit/delete-media-permanently',
		'npcink-abilities-toolkit/reply-comment',
		'npcink-abilities-toolkit/trash-comment',
		'npcink-abilities-toolkit/approve-comment',
		'NPCINK_OPENCLAW_ADAPTER_CORE_APP_TOKEN',
		'npcink_openclaw_adapter_core_app_token',
		'npcink_openclaw_adapter_approval_proxy_disabled',
		'approval_proxy_enabled=false',
		'approval_surface=npcink_governance_core_admin',
		'POST /wp-json/npcink-openclaw-adapter/v1/run-read-ability',
		'GET /wp-json/npcink-openclaw-adapter/v1/media-attachment-by-url?url={uploads_url}',
		'proposals:read',
		'audit_timeline',
		'Core Governance Audit is the governance log',
			'AI Request Logs are the provider request log',
			'adapter_request_id',
			'adapter_route',
			'explicit `ai_provider`',
			'explicit `ai_model`',
			'governance_source=npcink-governance-core',
		'npcink_governance_core.proposal_id',
		'npcink_governance_core.correlation_id',
		'governance_mode=direct_read',
		'governance_mode=proposal_required',
		'npcink-abilities-toolkit/build-content-inventory-fix-plan',
		'npcink-abilities-toolkit/build-test-content-cleanup-plan',
			'npcink-abilities-toolkit/build-media-inventory-fix-plan',
			'npcink-abilities-toolkit/build-media-reference-repair-plan',
			'npcink-abilities-toolkit/build-media-settings-reference-repair-plan',
			'npcink-abilities-toolkit/build-media-optimization-plan',
			'npcink-abilities-toolkit/build-media-rename-plan',
			'npcink-toolbox/build-article-write-plan',
			'npcink-toolbox/build-article-batch-write-plan',
			'npcink-toolbox/build-article-media-batch-write-plan',
			'npcink-toolbox/build-image-candidate-adoption-plan',
			'npcink-toolbox/build-ai-article-writing-pack',
			'openclaw_recipes.article_draft_plan',
			'openclaw_recipes.article_batch_draft_plan',
			'openclaw_recipes.article_media_batch_plan',
			'openclaw_recipes.image_candidate_adoption_plan',
			'docs/openclaw-ai-article-writing-pack-recipe.md',
			'The primary SEO/GEO/AEO entrypoint is',
			'Use `article-writing-pack` only for broad natural-language requests',
			'docs/openclaw-article-draft-plan-recipe.md',
			'docs/openclaw-article-batch-draft-plan-recipe.md',
			'docs/openclaw-article-media-batch-plan-recipe.md',
			'docs/openclaw-image-candidate-adoption-plan-recipe.md',
		'skipped_destructive_candidates',
		'write_actions',
		'Plan-to-proposal flow',
		'POST /npcink-governance-core/v1/proposals/from-plan',
		'core_proxy_execute=false',
		'commit_execution=false',
		'composer plugin-check:release',
		'composer package:release',
		'Local smoke and HTTP acceptance tests must register every created fixture',
		'automatic cleanup before assertions can fail',
		'negative-loop cases must not rely on final write execution',
		'.distignore',
		'Do not delete',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $readme, $required ), 'README contains required text: ' . $required );
}

$adapter_cli_package = maa_adapter_read( $root . '/packages/adapter-cli/package.json' );
foreach (
	array(
		'"name": "@npcink/openclaw-adapter-cli"',
		'"bin"',
		'"npcink-openclaw-adapter": "bin/npcink-openclaw-adapter.mjs"',
		'"node": ">=20"',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $adapter_cli_package, $required ), 'Adapter CLI package contains required text: ' . $required );
}

maa_adapter_assert( ! file_exists( $root . '/tools/npcink-openclaw-adapter.mjs' ), 'Root unified CLI wrapper is absent; use the npm CLI package.' );
maa_adapter_assert( ! file_exists( $root . '/tools/keypair-device-pairing.mjs' ), 'Root device-pairing wrapper is absent; use the npm CLI package.' );
maa_adapter_assert( ! file_exists( $root . '/tools/keypair-adapter-request.mjs' ), 'Root request wrapper is absent; use the npm CLI package.' );

$keypair_tool = maa_adapter_read( $root . '/packages/adapter-cli/bin/keypair-device-pairing.mjs' );
foreach (
	array(
		'generateKeyPairSync',
		'ed25519',
		'connect/device/start',
		'connect/device/poll',
		'X-Npcink-Key-Id',
		'X-Npcink-Signature',
		'Authorization',
		'Npcink-Signature',
		'MAGICK-AI-ADAPTER-V1',
		'insecure-local-tls',
		'no-open',
		'openApprovalUrl',
		'isRetryableNetworkError',
		'Transient polling error',
		'Health check failed after pairing',
		'Object.keys(value).length === 0',
		'private_key_jwk',
		'keypair-profiles',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $keypair_tool, $required ), 'Packaged keypair pairing tool contains expected behavior: ' . $required );
}
maa_adapter_assert( false === strpos( $keypair_tool, 'console.log(private' ), 'Keypair tool does not print private key material.' );

$keypair_request_tool = maa_adapter_read( $root . '/packages/adapter-cli/bin/keypair-adapter-request.mjs' );
foreach (
	array(
		'createPrivateKey',
		'private_key_jwk',
		'keypair-profiles',
		'isSafeAdapterRoute',
		'--body-file',
		'body-stdin',
		'--intent=preview|preflight|commit',
		'--query',
		'--query-string',
		'isFinalWriteRoute',
		'containsPreviewOnlyMarker',
		'enforceExecutionIntent',
		'Refusing final Adapter execute route without --intent=commit',
		'dry-run, commit=false, or commit_execution=false preview markers',
		'Npcink-Signature',
		'Authorization',
		'X-Npcink-Signature',
		'MAGICK-AI-ADAPTER-V1',
		'Object.keys(value).length === 0',
		'wrapper_failed',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $keypair_request_tool, $required ), 'Packaged keypair request wrapper contains expected behavior: ' . $required );
}
maa_adapter_assert( false === strpos( $keypair_request_tool, 'console.log(profile' ), 'Keypair request wrapper does not print profile data.' );
maa_adapter_assert( false === strpos( $keypair_request_tool, 'console.log(headers' ), 'Keypair request wrapper does not print signature headers.' );

$magick_adapter_tool = maa_adapter_read( $root . '/packages/adapter-cli/bin/npcink-openclaw-adapter.mjs' );
foreach (
	array(
		'connect',
		'status',
		'request',
		'keypair-device-pairing.mjs',
		'keypair-adapter-request.mjs',
		'missing_profile',
		'health_failed',
		'profile_path',
		'core_capabilities',
		'abilities_catalog',
		'commit_execution',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $magick_adapter_tool, $required ), 'Packaged unified local CLI contains expected behavior: ' . $required );
}
maa_adapter_assert( false === strpos( $magick_adapter_tool, 'private_key_jwk' ), 'Unified local CLI does not print or inspect private key material by name.' );

$wporg_readme = maa_adapter_read( $root . '/readme.txt' );
foreach (
	array(
		'=== Npcink OpenClaw Adapter ===',
		'Requires at least: 7.0',
		'Tested up to: 7.0',
		'Requires PHP: 8.0',
		'Stable tag: 0.1.0',
		'License: GPL-2.0-or-later',
		'Npcink Governance Core remains the governance backend',
		'npcink-abilities-toolkit/trash-post',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $wporg_readme, $required ), 'readme.txt contains required text: ' . $required );
}

$composer = maa_adapter_read( $root . '/composer.json' );
foreach (
	array(
		'"license": "GPL-2.0-or-later"',
		'"package:release"',
		'"plugin-check:release"',
		'--exclude-directories=tests,.git,vendor,node_modules,build,sj',
		'--exclude-files=.gitignore,.distignore,AGENTS.md,composer.json',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $composer, $required ), 'composer.json contains required text: ' . $required );
}

$distignore = maa_adapter_read( $root . '/.distignore' );
foreach (
	array(
		'.git',
		'.distignore',
		'.gitignore',
		'AGENTS.md',
		'build',
		'composer.json',
		'tests',
		'tools',
		'packages',
		'vendor',
		'node_modules',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $distignore, $required ), '.distignore excludes development artifact: ' . $required );
}

$quickstart = maa_adapter_read( $root . '/docs/openclaw-quickstart.md' );
foreach (
	array(
		'OpenClaw Quickstart',
		'OpenClaw only connects to Adapter',
		'https://magick-ai.local',
		'WordPress administrator username: `1`',
		'WordPress administrator password: `1`',
		'Application Password',
		'higher-security signed key-pair',
		'GET /health',
		'GET /help',
		'GET /capabilities',
		'Public Key Device Pairing',
		'cd ~ && npm exec --yes --package @npcink/openclaw-adapter-cli@0.1.0 -- npcink-openclaw-adapter',
		'does not keep root-level `tools/` compatibility',
		'connect/device/start',
		'POST /proposals/from-plan',
		'/proposals?limit=10',
		'/proposals/PROPOSAL_ID',
		'proposals:read',
		'audit_timeline',
		'NPCINK_OPENCLAW_ADAPTER_CORE_APP_TOKEN',
			'npcink_openclaw_adapter_core_app_token',
			'npcink_openclaw_adapter_approval_proxy_disabled',
			'approve-and-execute',
			'npcink_openclaw_adapter_execute_ability_not_allowed',
			'approval_proxy_enabled=false',
		'approval_surface=npcink_governance_core_admin',
		'log_context',
		'wpai_request_log_context',
		'proposal_id',
		'correlation_id',
		'adapter_request_id',
		'adapter_route',
		'ai_provider',
		'ai_model',
		'qwen3.5:0.8b',
		'/ai-provider-log-correlation-smoke',
		'Core Governance Audit is the governance log',
		'AI Request Logs are the provider request log',
			'/site-info',
			'/active-plugins-detail',
			'/plugin-conflict-diagnostics',
			'/recent-error-log',
			'/recent-error-log-tail',
			'/current-user-permissions',
			'/database-info',
			'/posts?author_id=1',
			'/terms?taxonomy=category&include_sample_posts=1',
			'/menu?location=primary',
		'/media?per_page=1',
		'/content-inventory-fix-plan?per_page=1&max_actions=1',
		'npcink-abilities-toolkit/build-content-inventory-fix-plan',
		'write_actions',
		'not as completed writes',
		'/pages?per_page=1',
		'wp-diagnostics-summary` to decide whether plugin details',
		'include_inactive_plugins=true',
		'Default inactive plugin rows are not missing',
		'error_log.summary.fatal_count',
		'not explicitly requested',
		'contents_included=true',
		'error_log.summary.by_severity',
			'Proposal-Required Write Flow',
			'core_proxy_execute=false',
			'commit_execution=false',
			'Dry-run-only verification stops at Adapter commit-preflight',
			'normalizes ability input to `dry_run=false` and `commit=true`',
			'execution_mode=batch_write_actions',
			'outside that execution allowlist',
		) as $required
) {
	maa_adapter_assert( false !== strpos( $quickstart, $required ), 'Quickstart contains required text: ' . $required );
}

$connection_model_notes = maa_adapter_read( $root . '/docs/openclaw-connection-model-notes.md' );
foreach (
	array(
		'OpenClaw Connection Model Notes',
		'Default: simple Application Password connection',
		'Higher security: local signed key-pair',
		'@npcink/openclaw-adapter-cli@0.1.0',
		'sh: npcink-openclaw-adapter: command not found',
		'Secret Handling Rules',
		'Plugin-generated private keys',
		'Adapter-owned MCP broker',
		'Core remains the proposal, approval, preflight, and audit truth',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $connection_model_notes, $required ), 'Connection model notes contain required text: ' . $required );
}

$contract = maa_adapter_read( $root . '/docs/openclaw-adapter-contract.md' );
foreach (
	array(
		'initial productization contract',
		'npcink-abilities-toolkit',
		'npcink-governance-core',
		'core_proxy_execute',
		'commit_execution',
		'Npcink -> Adapter',
		'Application Password Handoff',
		'Proposal Status Read Proxy',
			'Approval Disabled Stub Contract',
			'OpenClaw only connects to Adapter',
			'unified_action_route',
			'approve-and-execute',
			'show the raw password',
		'It must not store',
		'raw secrets in adapter options, manifest JSON, handoff text',
		'username `1` and password `1`',
		'Proposal-Required Write Flow',
		'Dry-run-only proposal verification stops at Adapter commit-preflight',
		'Adapter `execute`, `execute-approved-proposal`, and `approve-and-execute` routes are',
		'normalizes the ability input to `dry_run=false` and `commit=true`',
		'GET /wp-json/npcink-openclaw-adapter/v1/help',
		'GET /wp-json/npcink-openclaw-adapter/v1/proposals',
		'GET /wp-json/npcink-openclaw-adapter/v1/proposals/{proposal_id}',
		'POST /wp-json/npcink-openclaw-adapter/v1/proposals/from-plan',
		'POST /wp-json/npcink-openclaw-adapter/v1/proposals/{proposal_id}/execute',
		'POST /wp-json/npcink-openclaw-adapter/v1/proposals/{proposal_id}/approve-and-execute',
		'GET /wp-json/npcink-openclaw-adapter/v1/recent-error-log-tail',
		'GET /wp-json/npcink-openclaw-adapter/v1/plugin-conflict-diagnostics',
		'GET /wp-json/npcink-openclaw-adapter/v1/posts',
		'GET /wp-json/npcink-openclaw-adapter/v1/post-context',
		'GET /wp-json/npcink-openclaw-adapter/v1/users',
		'GET /wp-json/npcink-openclaw-adapter/v1/menu',
		'POST /wp-json/npcink-openclaw-adapter/v1/proposals/{proposal_id}/approve',
		'POST /wp-json/npcink-openclaw-adapter/v1/proposals/{proposal_id}/reject',
		'npcink_openclaw_adapter_approval_proxy_disabled',
		'approval_proxy_enabled=false',
		'approval_surface=npcink_governance_core_admin',
		'proposals:read',
		'audit_timeline',
		'AI Request Logs',
		'wp-diagnostics-summary` is only a quick overview',
		'POST /wp-json/npcink-openclaw-adapter/v1/ai-provider-log-correlation-smoke',
		'administrator-triggered diagnostics route',
		'production workload route',
		'prompt is used only for the bounded',
		'prompt management',
		'Core Governance Audit is the governance log',
		'AI Request Logs are the provider request log',
		'adapter_request_id',
		'adapter_route',
		'ai_provider',
		'ai_model',
		'qwen3.5:0.8b',
		'governance_source=npcink-governance-core',
		'npcink_governance_core.proposal_id',
		'npcink_governance_core.correlation_id',
		'include_log_contents',
		'include_inactive_plugins',
		'max_plugins_per_group',
		'tail_lines',
		'since_minutes',
		'not explicitly requested',
		'Inactive plugin rows are not requested by default',
		'fatal_count',
		'warning_count',
		'deprecated_count',
		'notice_count',
		'summary_source',
		'error_log.tail_entries',
		'error_log.summary.by_severity',
		'include_log_tail',
		'Npcink runtime, MCP, or cloud status',
		'plugin_file',
		'network_active',
		'dependency_count',
		'npcink_permissions',
		'severity_filter',
		'since_minutes',
		'author_id',
		'include_sample_posts',
		'author_profile',
		'attached_to',
		'npcink-abilities-toolkit/get-menu',
		'wpai_request_log_context',
		'log_context',
		'proposal_id',
		'correlation_id',
		'NPCINK_OPENCLAW_ADAPTER_CORE_APP_TOKEN',
		'npcink_openclaw_adapter_core_app_token',
		'Read-Only Planning Contract',
		'npcink-abilities-toolkit/build-content-inventory-fix-plan',
		'npcink-abilities-toolkit/build-test-content-cleanup-plan',
		'npcink-abilities-toolkit/build-media-inventory-fix-plan',
		'npcink-abilities-toolkit/build-media-reference-repair-plan',
		'npcink-abilities-toolkit/build-media-settings-reference-repair-plan',
		'npcink-toolbox/build-article-write-plan',
		'npcink-toolbox/build-article-batch-write-plan',
		'npcink-toolbox/build-article-media-batch-write-plan',
		'openclaw_recipes.article_batch_draft_plan',
		'openclaw_recipes.article_media_batch_plan',
		'Toolbox may expose click-driven buttons for the same fixed flows',
		'same ability ids, artifact',
		'Core proposal handoff routes',
		'OpenClaw recipe owner',
		'proposal truth, approval surface, or write executor',
		'article_batch_write_plan',
		'article_media_batch_write_plan',
		'skipped_destructive_candidates',
		'npcink-abilities-toolkit/delete-media-permanently',
		'Approved Proposal Execution Contract',
		'Unified Approve And Execute Contract',
		'openclaw-batch-execution-policy.md',
		'batch containing any non-allowlisted action fails',
		'npcink-abilities-toolkit/trash-post',
		'npcink-abilities-toolkit/create-draft',
		'npcink-abilities-toolkit/update-post',
		'npcink-abilities-toolkit/patch-post-content',
		'npcink-abilities-toolkit/patch-setting-value',
		'npcink-abilities-toolkit/set-post-seo-meta',
		'npcink-abilities-toolkit/set-post-slug',
		'npcink-abilities-toolkit/set-post-terms',
		'npcink-abilities-toolkit/delete-term',
		'npcink-abilities-toolkit/update-media-details',
		'npcink-abilities-toolkit/optimize-media-asset',
		'npcink-abilities-toolkit/replace-media-file',
		'npcink-abilities-toolkit/adopt-cloud-media-derivative',
		'npcink-abilities-toolkit/rename-media-file',
		'npcink-abilities-toolkit/delete-media-permanently',
		'npcink-abilities-toolkit/reply-comment',
		'npcink-abilities-toolkit/trash-comment',
		'npcink-abilities-toolkit/approve-comment',
		'execution profile registry',
		'capability discovery',
		'POST /proposals',
		'undeclared input fields',
		'invalid enum values',
		'`npcink-abilities-toolkit/update-post` does not accept `status`',
		'$outputs.<prior_action_id>.<field>',
		'cannot be embedded into larger strings',
		'POST /wp-json/npcink-governance-core/v1/proposals/from-plan',
		'The read path does not execute abilities marked `proposal_required`.',
		'The adapter does not store proposal governance state.',
		'explicit unified approve-and-execute action',
		'All routes require `manage_options`',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $contract, $required ), 'Adapter contract contains required text: ' . $required );
}

$acceptance = maa_adapter_read( $root . '/docs/openclaw-consumer-acceptance.md' );
foreach (
	array(
		'OpenClaw Consumer Acceptance',
		'OpenClaw must not connect directly to Npcink Governance Core for productized use.',
		'GET /health',
		'GET /help',
		'GET /capabilities',
		'GET /proposals',
		'GET /proposals/{proposal_id}',
		'POST /proposals',
		'POST /proposals/from-plan',
		'POST /proposals/{proposal_id}/commit-preflight',
		'POST /proposals/{proposal_id}/execute',
		'POST /proposals/{proposal_id}/approve-and-execute',
		'execution_mode=batch_write_actions',
		'For dry-run-only validation, stop at this step and do not call',
		'normalized ability input to `dry_run=false` and',
		'status=failed',
		'failed action metadata',
		'does not store the full proposal or create a retry queue',
		'npcink_openclaw_adapter_write_action_invalid',
		'approved proposal execution',
		'approve-and-execute',
		'npcink-abilities-toolkit/trash-post',
		'npcink-abilities-toolkit/create-draft',
		'npcink-abilities-toolkit/update-post',
		'npcink-abilities-toolkit/patch-post-content',
		'npcink-abilities-toolkit/patch-setting-value',
		'npcink-abilities-toolkit/set-post-seo-meta',
		'npcink-abilities-toolkit/set-post-slug',
		'npcink-abilities-toolkit/set-post-terms',
		'npcink-abilities-toolkit/delete-term',
		'npcink-abilities-toolkit/update-media-details',
		'npcink-abilities-toolkit/delete-media-permanently',
		'npcink-abilities-toolkit/reply-comment',
		'npcink-abilities-toolkit/trash-comment',
		'npcink-abilities-toolkit/approve-comment',
		'active-plugins-detail',
		'plugin-conflict-diagnostics',
		'current-user-permissions',
		'database-info',
		'recent-error-log-tail',
		'wp-ops-diagnostics-detail',
		'include_log_contents=false',
		'include_inactive_plugins=false',
		'include_inactive_plugins=true',
		'not explicitly',
		'error_log.summary.fatal_count',
		'error_log.tail_entries',
		'error_log.summary.by_severity',
		'Core Governance Audit',
		'AI Request Logs',
		'POST /ai-provider-log-correlation-smoke',
		'configured text',
		'generation provider/model',
		'explicit `ai_provider`',
		'`ai_model` sent to the provider smoke',
		'adapter_request_id',
		'governance_source=npcink-governance-core',
		'provider request log',
		'npcink_openclaw_adapter_approval_proxy_disabled',
		'npcink-abilities-toolkit/build-content-inventory-fix-plan',
		'npcink-abilities-toolkit/build-test-content-cleanup-plan',
		'npcink-abilities-toolkit/build-media-inventory-fix-plan',
		'npcink-abilities-toolkit/build-media-reference-repair-plan',
		'npcink-abilities-toolkit/build-media-settings-reference-repair-plan',
		'npcink-toolbox/build-article-write-plan',
		'npcink-toolbox/build-article-batch-write-plan',
		'npcink-toolbox/build-article-media-batch-write-plan',
		'openclaw_recipes.article_batch_draft_plan',
		'openclaw_recipes.article_media_batch_plan',
		'npcink-toolbox/build-content-discoverability-brief',
		'primary_contract=true',
		'`seo`,',
		'`aeo`,',
		'`geo`,',
		'`exceptions`,',
		'`special_cases`,',
		'`proposal_allowed_fields`',
		'primary SEO/GEO/AEO entrypoint',
		'plan-to-proposal forwarding',
		'skipped_destructive_candidates',
		'write_actions',
		'commit_execution=false',
		'no new runtime ownership',
		'composer plugin-check:release',
		'composer package:release',
		'Local Fixture Cleanup',
		'Local smoke and HTTP acceptance fixtures must be registered',
		'cleanup before any assertion that can fail',
		'register_shutdown_function',
		'try/finally',
		'Core proposal rows',
		'Core audit rows',
		'Adapter execution',
		'Negative Loop Reject Fixture',
		'Negative Loop Preflight Fixture',
		'OpenClaw HTTP acceptance draft',
		'Operator Loop Article Draft',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $acceptance, $required ), 'OpenClaw acceptance doc contains required text: ' . $required );
}

$agents = maa_adapter_read( $root . '/AGENTS.md' );
foreach (
	array(
		'thin OpenClaw channel layer',
		'does not own',
		'explicit post-Core execution profile policy',
		'generic final write authority',
		'admin-authenticated AI Request Logs correlation smoke route',
		'manual diagnostics route',
		'not model routing, prompt management, product UX, or',
		'npcink-cloud-addon',
		'Do not add Adapter-owned Cloud',
		'npcink-abilities-toolkit',
		'npcink-governance-core',
		'core_proxy_execute=false',
		'commit_execution=false',
		'composer plugin-check:release',
		'composer package:release',
		'.distignore',
) as $required
) {
	maa_adapter_assert( false !== strpos( $agents, $required ), 'AGENTS.md contains required text: ' . $required );
}
maa_adapter_assert(
	false === strpos( $agents, "- final write execution policy;" ),
	'AGENTS.md no longer forbids the explicit post-Core execution profile policy.'
);

$smoke_sh = maa_adapter_read( $root . '/tests/smoke-wp.sh' );
foreach (
	array(
		'wp-content/plugins/npcink-openclaw-adapter',
		'wp plugin activate npcink-openclaw-adapter',
		'eval-file "$ROOT_DIR/tests/smoke-wp.php"',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $smoke_sh, $required ), 'Smoke shell contains required text: ' . $required );
}

$smoke_wp = maa_adapter_read( $root . '/tests/smoke-wp.php' );
foreach (
	array(
		'/npcink-openclaw-adapter/v1/health',
		'/npcink-openclaw-adapter/v1/help',
		'/npcink-openclaw-adapter/v1/capabilities',
			'/npcink-openclaw-adapter/v1/site-summary',
			'/npcink-openclaw-adapter/v1/wp-diagnostics-summary',
			'/npcink-openclaw-adapter/v1/active-plugins-detail',
			'/npcink-openclaw-adapter/v1/plugin-conflict-diagnostics',
			'/npcink-openclaw-adapter/v1/recent-error-log',
			'/npcink-openclaw-adapter/v1/recent-error-log-tail',
			'/npcink-openclaw-adapter/v1/current-user-permissions',
			'/npcink-openclaw-adapter/v1/database-info',
			'/npcink-openclaw-adapter/v1/cron-events-detail',
			'/npcink-openclaw-adapter/v1/workflow-recipes',
		'/npcink-openclaw-adapter/v1/workflow-recipe',
		'OpenClaw article draft plan entrypoint ability',
		'adapter forwards Toolbox article plan to Core',
		'adapter article plan creates one Core proposal',
		'adapter article plan creates only a WordPress draft',
		'/npcink-openclaw-adapter/v1/proposals',
		'/npcink-openclaw-adapter/v1/proposals/from-plan',
		'adapter plan-to-proposal rejects invalid profiled action input before Core forwarding',
		'invalid-update-post-status',
		'adapter plan action input rejection carries field',
		'adapter from-plan output references create one batch proposal',
		'adapter from-plan output-reference batch approve-and-execute succeeds',
		'adapter plan-to-proposal rejects duplicate action ids before Core forwarding',
		'adapter plan-to-proposal rejects embedded output reference tokens before Core forwarding',
		'adapter batch approve-and-execute rejects embedded output reference tokens before execution',
		'/execute',
		'/npcink-openclaw-adapter/v1/execute-approved-proposal',
		'/approve-and-execute',
		'/npcink-openclaw-adapter/v1/ai-provider-log-correlation-smoke',
		'/ai/v1/logs',
		'/npcink-governance-core/v1/audit',
			'npcink-abilities-toolkit/site-summary',
			'npcink-abilities-toolkit/wp-diagnostics-summary',
			'npcink-abilities-toolkit/wp-ops-diagnostics-detail',
			'npcink-abilities-toolkit/list-workflow-recipes',
		'npcink-abilities-toolkit/get-workflow-recipe',
		'npcink-abilities-toolkit/build-content-inventory-fix-plan',
		'npcink-abilities-toolkit/build-test-content-cleanup-plan',
		'npcink-abilities-toolkit/build-media-inventory-fix-plan',
		'npcink-abilities-toolkit/build-media-reference-repair-plan',
		'npcink-abilities-toolkit/build-media-settings-reference-repair-plan',
		'npcink-toolbox/build-article-write-plan',
		'npcink-abilities-toolkit/list-posts',
		'npcink-abilities-toolkit/get-post-context',
		'npcink-abilities-toolkit/list-users',
		'npcink-abilities-toolkit/get-menu',
		'include_log_contents',
		'include_inactive_plugins',
		'max_plugins_per_group',
		'tail_entries',
		'by_severity',
		'plugin conflict diagnostic requests inactive plugin rows',
		'default error log diagnostic exposes severity summary without log contents',
		'adapter_request_id',
		'adapter_route',
		'ai_provider',
		'ai_model',
		'governance_source',
		'npcink_governance_core',
		'qwen3.5:0.8b',
		'adapter refuses direct execution for proposal-required ability',
		'adapter refuses direct execution for destructive ability',
		'adapter health exposes approved proposal execution route',
		'adapter health exposes approve-and-execute route',
		'adapter health exposes trash-post execute allowlist',
		'adapter health exposes rename-media-file execute allowlist',
		'adapter health exposes delete-media-permanently execute allowlist',
		'adapter help exposes execute-approved-proposal route',
		'adapter help exposes proposal execute route',
		'adapter help exposes proposal approve-and-execute route',
		'adapter smoke created trash-post fixture',
		'adapter creates trash-post proposal for approved execution smoke',
		'adapter trash-post proposal starts pending',
		'adapter execute refuses pending proposal',
		'adapter pending execute leaves post published',
		'Core admin REST approval succeeds for adapter trash execution smoke',
		'adapter executes approved trash-post proposal',
		'adapter execute response carries proposal id',
		'adapter execute response carries ability id',
		'adapter execute response carries correlation id',
		'adapter execute response carries adapter request id',
		'adapter execute response carries approval context',
		'adapter execute response preserves commit_execution=false',
		'adapter execute trashes post',
		'adapter execute returns non-dry-run ability result',
		'adapter approved execution moves post to trash',
		'adapter rejects duplicate approved proposal execution',
		'adapter duplicate execute uses completed execution error code',
		'adapter duplicate execute returns stored execution record',
		'adapter duplicate execute preserves original adapter request id',
		'adapter creates trash-post proposal for approve-and-execute smoke',
		'adapter approve-and-execute succeeds for pending trash-post proposal',
		'adapter approve-and-execute response carries proposal id',
		'adapter approve-and-execute response carries ability id',
		'adapter approve-and-execute response carries post id',
		'adapter approve-and-execute records pending status before approval',
		'adapter approve-and-execute auto approves pending proposal through Core',
		'adapter approve-and-execute response carries correlation id',
		'adapter approve-and-execute preserves Core commit_execution=false',
		'adapter approve-and-execute records post status before execution',
		'adapter approve-and-execute records post status after execution',
		'adapter approve-and-execute execution result succeeds',
		'adapter approve-and-execute moves pending proposal post to trash',
		'adapter rejects duplicate approve-and-execute request',
		'adapter duplicate approve-and-execute uses completed execution error code',
		'adapter duplicate approve-and-execute returns stored execution record',
		'adapter duplicate approve-and-execute preserves original adapter request id',
		'adapter rejects duplicate create-draft approve-and-execute request',
		'adapter creates write_actions batch proposal for approve-and-execute smoke',
		'adapter batch approve-and-execute succeeds for allowlisted write_actions',
		'adapter batch approve-and-execute reports batch execution mode',
		'adapter batch approve-and-execute returns per-action results',
		'adapter creates output-reference write_actions batch proposal',
		'adapter batch approve-and-execute succeeds with output references',
		'adapter output-reference batch updates the created draft',
		'adapter output-reference batch leaves created draft trashed',
		'adapter batch approve-and-execute rejects non-allowlisted write_action',
		'adapter bad batch does not execute allowed action before failing closed',
		'adapter approve-and-execute succeeds for already approved proposal',
		'adapter approve-and-execute records approved status before execution',
		'adapter approve-and-execute skips approve for already approved proposal',
		'adapter approve-and-execute moves already approved post to trash',
		'adapter approve-and-execute rejects rejected proposal',
		'adapter rejected proposal response returns operator feedback',
		'adapter rejected proposal feedback preserves Core rejection note',
		'adapter approve-and-execute does not execute rejected proposal',
		'adapter approve-and-execute returns preflight failure',
		'adapter preflight-blocked response returns operator feedback',
		'adapter preflight-blocked feedback preserves no Core execution',
		'adapter approve-and-execute does not execute preflight-blocked proposal',
		'adapter article plan handoff returns operator feedback',
		'adapter article plan handoff feedback preserves Core error code',
		'adapter article plan handoff feedback marks revision retryable',
		'adapter proposal create rejects update-post without update fields',
		'adapter proposal create rejects update-post status input',
		'adapter update-post status rejection uses schema field error code',
		'adapter creates set-post-seo-meta proposal for approve-and-execute smoke',
		'adapter proposal create rejects set-post-seo-meta without SEO fields',
		'adapter creates set-post-slug proposal for approve-and-execute smoke',
		'adapter proposal create rejects set-post-slug without valid slug',
		'adapter rejects duplicate set-post-terms approve-and-execute request',
		'adapter proposal create rejects set-post-terms without terms',
		'adapter proposal create rejects set-post-terms create_missing',
		'adapter creates delete-term proposal for approve-and-execute smoke',
		'adapter approve-and-execute succeeds for pending delete-term proposal',
		'adapter proposal create rejects delete-term without term_id',
		'adapter proposal create rejects delete-term invalid taxonomy',
		'adapter creates update-media-details proposal for approve-and-execute smoke',
		'adapter proposal create rejects update-media-details without detail fields',
		'adapter creates rename-media-file proposal for dry-run preflight smoke',
		'Core admin REST approval succeeds for rename-media-file dry-run preflight smoke',
		'adapter rename-media-file dry-run preflight preserves Core commit_execution=false',
		'adapter rename-media-file dry-run preflight caches handoff without executing',
		'adapter rename-media-file dry-run preflight leaves attached file pointer unchanged',
		'adapter rename-media-file dry-run preflight leaves media URL unchanged',
		'adapter rename-media-file dry-run preflight leaves original media file in place',
		'adapter creates rename-media-file proposal for approve-and-execute smoke',
		'adapter approve-and-execute succeeds for pending rename-media-file proposal',
		'adapter approve-and-execute response carries rename-media-file ability id',
		'adapter rename-media-file execution returns non-dry-run ability result',
		'adapter rename-media-file execution reports rename',
		'adapter rename-media-file commit updates attached file pointer',
		'adapter rename-media-file commit moves old media file',
		'adapter rename-media-file commit writes target media file',
		'adapter rename-media-file commit changes media URL',
		'adapter rename-media-file commit URL contains target file name',
		'adapter creates delete-media-permanently proposal for approve-and-execute smoke',
		'adapter approve-and-execute succeeds for pending delete-media-permanently proposal',
		'adapter approve-and-execute deletes media attachment permanently',
		'adapter proposal create rejects delete-media-permanently without attachment_id',
		'adapter proposal create rejects delete-media-permanently for non-attachment post',
		'adapter proposal create rejects reply-comment without content',
		'adapter creates trash-comment proposal for approve-and-execute smoke',
		'adapter proposal create rejects trash-comment without comment_id',
		'adapter proposal create rejects approve-comment without comment_id',
		'adapter approve-and-execute rejects non-allowlisted ability',
		'adapter capabilities expose content inventory fix plan through Core',
		'adapter capabilities expose test content cleanup plan through Core',
		'adapter capabilities expose media inventory fix plan through Core',
		'adapter plan read preserves write_actions',
		'adapter plan read preserves preview',
		'adapter plan read preserves commit_execution=false',
		'adapter plan read carries internal read policy',
		'adapter diagnostics read applies sensitive redaction policy',
		'adapter read response carries generated correlation id',
		'adapter media plan preserves skipped destructive candidates field',
		'adapter media plan does not promote skipped deletes into write actions by default',
		'adapter media plan shortcut treats include_delete_candidates=false as false',
		'adapter media plan shortcut treats include_trash_parent_media=false as false',
		'adapter media plan shortcut treats include_unattached_test_media=false as false',
		'adapter forwards plan-to-proposal route to Core',
		'adapter rejects unallowed plan-to-proposal ability before Core forwarding',
		'adapter plan proposal caller carries adapter request id',
		'adapter e2e media plan creates Core proposal',
		'adapter e2e plan proposal detail preserves source plan preview',
		'adapter e2e plan proposal detail preserves manual review rows',
		'adapter e2e plan proposal detail preserves skipped destructive candidates',
		'adapter e2e media plan keeps delete-media-permanently out of created proposals by default',
		'adapter plan-to-proposal response preserves proposal list state',
		'adapter help exposes proposal list route',
		'adapter help exposes proposal detail route',
		'adapter help keeps approval proxy disabled',
		'adapter help keeps rejection proxy disabled',
		'adapter health exposes Core app token configured state without token value',
		'adapter help exposes Core app token configured state without token value',
		'adapter smoke created scoped Core app token',
		'adapter Core app token does not include approval scope',
		'adapter Core app token does not include audit read scope',
		'adapter creates proposal through Core app token',
		'adapter app-token proposal stores app attribution',
		'adapter app-token commit preflight returns policy version',
		'adapter app-token commit preflight hash matches proposal input',
		'adapter app-token error response',
		'Core audit stores Adapter app attribution for proposal creation',
		'Core audit stores Adapter app attribution for commit preflight',
		'adapter returns created proposal in Core proposal list',
		'adapter returns proposal detail through Core',
		'adapter proposal detail preserves audit timeline',
		'adapter read response exposes AI request log context',
		'adapter read log context carries proposal id',
			'adapter read log context carries correlation id',
			'adapter active plugins shortcut uses ops diagnostics detail',
			'adapter runs active plugins diagnostic shortcut through ops detail',
			'adapter runs current user permissions diagnostic shortcut through ops detail',
			'adapter runs explicit error log tail diagnostic through ops detail',
			'default error log diagnostic does not include log contents',
			'explicit error log tail diagnostic exposes redacted tail entries',
			'adapter runs database diagnostic shortcut',
			'adapter runs cron events diagnostic shortcut',
		'adapter approval stub returns disabled response',
			'adapter rejection stub returns disabled response',
			'adapter approval stub does not change Core proposal status',
			'adapter rejection stub does not change Core proposal status',
			'maa_adapter_smoke_text_generation_model',
			'AI provider smoke found a configured text generation model',
			'adapter provider smoke succeeds with configured text model',
			'adapter provider smoke context carries selected provider',
		'adapter provider smoke context carries selected model',
		'AI Request Logs context contains proposal id',
		'AI Request Logs context contains correlation id',
		'maa_adapter_smoke_capture_observability_event',
		'adapter emits OpenClaw dispatch completed event for health',
		'adapter emits OpenClaw dispatch failed event for plan handoff failure',
		'adapter emits Core relay success event for capabilities',
		'adapter emits Core relay failure event for missing proposal',
		'adapter emits proposal create success observability event',
		'adapter emits proposal create failure observability event',
		'adapter emits plan handoff success observability event',
		'adapter emits plan handoff failure observability event',
		'adapter emits commit preflight success observability event',
		'adapter emits commit preflight failure observability event',
			'adapter health exposes AI article writing pack shortcut',
			'adapter help exposes AI article writing pack shortcut',
			'adapter help exposes AI article writing pack recipe entrypoint ability',
			'adapter help marks AI article writing recipe as no direct write',
			'adapter runs content discoverability brief primary ability',
			'content discoverability brief returns the expected artifact type',
			'content discoverability brief is marked as the primary SEO/GEO/AEO contract',
			'content discoverability brief is suggestion-only',
			'content discoverability brief points final writes to Core proposals',
			'content discoverability brief disables direct WordPress writes',
			'content discoverability brief exposes SEO section',
			'content discoverability brief exposes AEO section',
			'content discoverability brief exposes GEO section',
			'content discoverability brief exposes exceptions',
			'content discoverability brief exposes special cases',
			'content discoverability brief exposes proposal allowed fields',
			'excludes raw key ',
		'AI Request Logs context contains explicit provider even if provider column is blank',
		'AI Request Logs context contains explicit model even if provider column is blank',
		'Core Governance Audit filters by the same provider smoke correlation id',
		'maa_adapter_smoke_fixture_registry',
		'maa_adapter_smoke_register_attachment_fixture',
		'_npcink_openclaw_adapter_smoke_fixture_run_id',
		'maa_adapter_smoke_known_media_fixture_leak_ids',
		'maa_adapter_smoke_known_media_fixture_file_paths',
		'codex-commit-',
		'maa_adapter_smoke_assert_no_media_fixture_leaks',
		'maa_adapter_smoke_cleanup_registered_fixtures',
		'register_shutdown_function',
		'npcink_openclaw_adapter_execution_records',
		'npcink_openclaw_adapter_preflight_handoffs',
		'md5( $cleanup_proposal_id )',
		'adapter cached preflight handoff execute succeeds',
		'adapter failed execution returns failed execution record',
		'adapter failed execution record carries ability error code',
		'adapter failed execution record keeps commit_execution=false',
		'adapter status smoke cleaned created proposal records',
		'adapter smoke leaves no registered or reserved-prefix media fixtures behind',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $smoke_wp, $required ), 'WordPress smoke contains required text: ' . $required );
}

$article_recipe = maa_adapter_read( $root . '/docs/openclaw-article-draft-plan-recipe.md' );
foreach (
	array(
		'OpenClaw Article Draft Plan Recipe',
		'npcink-toolbox/build-article-write-plan',
		'npcink-abilities-toolkit/create-draft',
		'POST /wp-json/npcink-openclaw-adapter/v1/run-read-ability',
		'POST /wp-json/npcink-openclaw-adapter/v1/proposals/from-plan',
		'POST /wp-json/npcink-openclaw-adapter/v1/proposals/{proposal_id}/approve-and-execute',
		'artifact_type=article_write_plan',
		'risk_level=high',
		'blocked_claims',
		'Cloud Addon is not part of this local control loop',
		'Adapter must not publish, schedule, approve standalone, or execute arbitrary writes',
		'local article assistant handoff',
		'not a bulk writing flow',
		'hosted drafting path',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $article_recipe, $required ), 'Article draft recipe contains required text: ' . $required );
}

$article_batch_recipe = maa_adapter_read( $root . '/docs/openclaw-article-batch-draft-plan-recipe.md' );
foreach (
	array(
		'OpenClaw Article Batch Draft Plan Recipe',
		'npcink-toolbox/build-article-batch-write-plan',
		'article_batch_write_plan',
		'proposal_mode=batch',
		'batch_approval=true',
		'npcink-abilities-toolkit/create-draft',
		'POST /wp-json/npcink-openclaw-adapter/v1/run-read-ability',
		'POST /wp-json/npcink-openclaw-adapter/v1/proposals/from-plan',
		'POST /wp-json/npcink-openclaw-adapter/v1/proposals/{proposal_id}/approve-and-execute',
		'status=draft',
		'core_proxy_execute=false',
		'commit_execution=false',
		'publish_allowed=false',
		'partial_success=false',
		'fail closed',
		'not make Adapter the article generator',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $article_batch_recipe, $required ), 'Article batch draft recipe contains required text: ' . $required );
}

$content_discoverability_recipe = maa_adapter_read( $root . '/docs/openclaw-content-discoverability-recipe.md' );
foreach (
	array(
		'OpenClaw Content Discoverability Recipe',
		'The primary SEO/GEO/AEO entrypoint is `content-discoverability-brief`',
		'Use `article-writing-pack` only for broad natural-language requests',
		'openclaw_recipes.ai_article_draft_with_discoverability',
		'GET /wp-json/npcink-openclaw-adapter/v1/article-writing-pack?topic=TOPIC',
		'npcink-toolbox/validate-content-discoverability-context',
		'npcink-toolbox/get-content-discoverability-context',
		'npcink-toolbox/build-content-discoverability-brief',
		'GET /wp-json/npcink-openclaw-adapter/v1/content-discoverability-validation',
		'GET /wp-json/npcink-openclaw-adapter/v1/content-discoverability-context',
		'GET /wp-json/npcink-openclaw-adapter/v1/content-discoverability-brief?post_id=POST_ID',
		'"search_policy"',
		'"requires_external_evidence": true',
		'"max_results": 3',
		'"recency_days": 30',
		'"enhance_with_reader": false',
		'Cloud owns the search providers',
		'cloud_evidence.web_search',
		'governance_mode=direct_read',
		'execution_surface=wp_abilities_rest',
		'write_posture',
		'suggestion_only',
		'direct_wordpress_write',
		'final_write_path',
		'core_proposal_required',
		'Do not add these Toolbox abilities to Adapter',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $content_discoverability_recipe, $required ), 'Content discoverability recipe contains required text: ' . $required );
}

$article_writing_pack_recipe = maa_adapter_read( $root . '/docs/openclaw-ai-article-writing-pack-recipe.md' );
foreach (
	array(
		'OpenClaw AI Article Writing Pack Recipe',
		'For SEO/GEO/AEO suggestions on a known post',
		'Use `article-writing-pack` only for broad natural-language requests',
		'npcink-toolbox/build-ai-article-writing-pack',
		'GET /wp-json/npcink-openclaw-adapter/v1/article-writing-pack?topic=AI_TOPIC',
		'"search_policy"',
		'"requires_external_evidence": true',
		'"max_results": 3',
		'"recency_days": 30',
		'"enhance_with_reader": false',
		'Cloud owns the search providers',
		'cloud_evidence.web_search when external evidence is available',
		'governance_mode=direct_read',
		'execution_surface=wp_abilities_rest',
		'artifact_type=ai_article_writing_pack',
		'write_posture=suggestion_only',
		'direct_wordpress_write=false',
		'provider_execution=none',
		'final_write_path=core_proposal_required',
		'npcink-toolbox/build-article-write-plan',
		'npcink-toolbox/build-article-batch-write-plan',
		'npcink-toolbox/build-article-media-batch-write-plan',
		'POST /wp-json/npcink-openclaw-adapter/v1/proposals/from-plan',
		'Do not publish, schedule, upload media, set featured images, write SEO meta',
		'not an article generator product',
		'local review candidate',
		'batch article writing',
		'article drafts that also include selected image-source',
		'Do not present OpenClaw as the article generator',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $article_writing_pack_recipe, $required ), 'AI article writing pack recipe contains required text: ' . $required );
}

$article_media_batch_recipe = maa_adapter_read( $root . '/docs/openclaw-article-media-batch-plan-recipe.md' );
foreach (
	array(
		'OpenClaw Article Media Batch Plan Recipe',
		'npcink-toolbox/build-article-media-batch-write-plan',
		'article_media_batch_write_plan',
		'npcink-toolbox/search-image-source',
		'npcink-abilities-toolkit/create-draft',
		'npcink-abilities-toolkit/upload-media-from-url',
		'npcink-abilities-toolkit/update-media-details',
		'npcink-abilities-toolkit/set-post-featured-image',
		'POST /wp-json/npcink-openclaw-adapter/v1/proposals/from-plan',
		'POST /wp-json/npcink-openclaw-adapter/v1/proposals/{proposal_id}/approve-and-execute',
		'image source attribution is preserved',
		'core_proxy_execute=false',
		'commit_execution=false',
		'publish_allowed=false',
		'partial_success=false',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $article_media_batch_recipe, $required ), 'Article media batch recipe contains required text: ' . $required );
}

$image_candidate_adoption_recipe = maa_adapter_read( $root . '/docs/openclaw-image-candidate-adoption-plan-recipe.md' );
foreach (
	array(
		'OpenClaw Image Candidate Adoption Plan Recipe',
		'npcink-toolbox/build-image-candidate-adoption-plan',
		'image_candidate_adoption_plan',
		'image_candidate.v1',
		'npcink-toolbox/search-image-source',
		'npcink-abilities-toolkit/upload-media-from-url',
		'npcink-abilities-toolkit/update-media-details',
		'npcink-abilities-toolkit/set-post-featured-image',
		'POST /wp-json/npcink-openclaw-adapter/v1/proposals/from-plan',
		'POST /wp-json/npcink-openclaw-adapter/v1/proposals/{proposal_id}/approve-and-execute',
		'core_proxy_execute=false',
		'commit_execution=false',
		'cloud_control_plane=false',
		'Adapter does not search providers, generate images, import media',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $image_candidate_adoption_recipe, $required ), 'Image candidate adoption recipe contains required text: ' . $required );
}

$batch_policy = maa_adapter_read( $root . '/docs/openclaw-batch-execution-policy.md' );
foreach (
	array(
		'OpenClaw Batch Execution Policy',
		'Status: accepted',
		'target_ability_id=npcink-abilities-toolkit/trash-post',
		'target_ability_id=npcink-abilities-toolkit/set-post-seo-meta',
		'target_ability_id=npcink-abilities-toolkit/update-post',
		'target_ability_id=npcink-abilities-toolkit/patch-post-content',
		'target_ability_id=npcink-abilities-toolkit/patch-setting-value',
		'target_ability_id=npcink-abilities-toolkit/set-post-slug',
		'target_ability_id=npcink-abilities-toolkit/set-post-terms',
		'target_ability_id=npcink-abilities-toolkit/delete-term',
		'target_ability_id=npcink-abilities-toolkit/update-media-details',
		'target_ability_id=npcink-abilities-toolkit/upload-media-from-url',
		'target_ability_id=npcink-abilities-toolkit/set-post-featured-image',
		'target_ability_id=npcink-abilities-toolkit/optimize-media-asset',
		'target_ability_id=npcink-abilities-toolkit/replace-media-file',
		'target_ability_id=npcink-abilities-toolkit/adopt-cloud-media-derivative',
		'target_ability_id=npcink-abilities-toolkit/rename-media-file',
		'target_ability_id=npcink-abilities-toolkit/delete-media-permanently',
		'target_ability_id=npcink-abilities-toolkit/reply-comment',
		'target_ability_id=npcink-abilities-toolkit/trash-comment',
		'target_ability_id=npcink-abilities-toolkit/approve-comment',
		'Execution Profile Registry',
		'Capability discovery is not enough to execute a write ability',
		'Adapter validates proposal input at `POST /proposals`',
		'POST /proposals/from-plan',
		'npcink_openclaw_adapter_plan_action_input_invalid',
		'$outputs.<prior_action_id>.<field>',
		'invalid enum values',
		'$outputs.<prior_action_id>.<field>',
		'cannot point forward',
		'cannot be embedded into larger strings',
		'fail closed',
		'Maximum batch size is 200 actions',
		'Partial success is not a normal success mode',
		'execution_mode=batch_write_actions',
		'expand the Adapter execution allowlist',
		'turn disabled approve/reject stubs into real proxies',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $batch_policy, $required ), 'Batch execution policy contains required text: ' . $required );
}

echo "Static contracts: ok\n";
