<?php
/**
 * Static contracts for Magick AI Adapter.
 *
 * @package MagickAIAdapter
 */

$root = dirname( __DIR__ );

/**
 * Assertion helper.
 *
 * @param bool   $condition Condition.
 * @param string $message Message.
 * @return void
 */
function maa_adapter_assert( bool $condition, string $message ): void {
	if ( ! $condition ) {
		fwrite( STDERR, '[fail] ' . $message . "\n" );
		exit( 1 );
	}
}

/**
 * Reads a file.
 *
 * @param string $path Path.
 * @return string
 */
function maa_adapter_read( string $path ): string {
	$contents = is_readable( $path ) ? file_get_contents( $path ) : false;
	return is_string( $contents ) ? $contents : '';
}

$main = maa_adapter_read( $root . '/magick-ai-adapter.php' );
maa_adapter_assert( false !== strpos( $main, 'Plugin Name: Magick AI Adapter' ), 'Main plugin has WordPress plugin header.' );
maa_adapter_assert( false !== strpos( $main, 'License: GPL-2.0-or-later' ), 'Main plugin declares GPL-compatible license.' );
maa_adapter_assert( false !== strpos( $main, 'plugins_loaded' ), 'Main plugin boots on plugins_loaded.' );

$controller = maa_adapter_read( $root . '/includes/Rest/Controller.php' );
foreach (
	array(
		'magick-ai-adapter/v1',
		'/health',
		'/help',
		'/capabilities',
		'/connection/manifest',
		'/connect/device/start',
		'/connect/device/poll',
		'/connection/key-pairs',
		'connection_manifest',
		'start_device_pairing',
		'poll_device_pairing',
		'approve_device_pairing',
		'revoke_client_key_by_id',
		'authenticate_signed_request',
		'signed_request_credentials',
		'DEVICE_PAIRING_TTL',
		'SIGNATURE_NONCE_TTL',
		'key_pair_device_pairing',
		'magick-key-pair-auth.v1',
		'x_magick_key_id',
		'Magick-Signature',
		'Ed25519',
		'/run-read-ability',
		'/ai-provider-log-correlation-smoke',
		'ai_provider_log_correlation_smoke',
		'/site-info',
		'/site-summary',
			'/wp-diagnostics-summary',
			'/wp-ops-diagnostics-detail',
			'active-plugins-detail',
			'plugin-conflict-diagnostics',
			'current-user-permissions',
			'php-extensions',
			'object-cache-status',
			'rewrite-rules-status',
			'ssl-https-status',
			'recent-error-log',
			'recent-error-log-tail',
			'database-info',
			'cron-events-detail',
			'custom-post-types',
			'roles-capabilities',
			'widgets-sidebars',
			'block-theme-assets',
			'search-index-status',
			'server-info',
			'integrations-status',
			'seo-summary',
			'security-summary',
			'performance-summary',
			'read_shortcut_definitions',
			'ops_diagnostics_input',
			'ops_diagnostics_plugin_conflict_input',
			'ops_diagnostics_log_input',
			'include_log_contents',
			'include_active_plugins',
			'include_inactive_plugins',
			'include_plugin_updates',
			'include_must_use_plugins',
			'include_dropins',
			'max_plugins_per_group',
			'tail_lines',
			'since_minutes',
			'not explicitly requested',
			'inactive plugin rows are not requested by default',
			'route_groups',
			'help_route_groups',
			'help_routes_flat',
			'help_route_purpose',
			'GET /term?id={id}',
			'normalize_shortcut_input',
			'boolean_input_value',
			'include_delete_candidates',
			'allowed_plan_ability_ids',
			'magick_ai_adapter_plan_ability_not_allowed',
			'execution_profiles',
			'validate_proposal_create_input',
			'validate_plan_write_action_inputs',
			'invalid_output_reference_token',
			'allowed_execute_ability_ids',
			'allowed_input_fields',
			'enum_fields',
			'magick_ai_adapter_ability_input_field_not_allowed',
			'magick_ai_adapter_plan_action_input_invalid',
			'validate_output_references',
			'resolve_output_references',
			'magick_ai_adapter_output_reference_unavailable',
			'magick_ai_adapter_output_reference_unresolved',
			'post_id_from_result',
			'force_post_input',
			'required_slug_fields',
			'validate_terms_input',
			'validate_delete_term_input',
			'execute_approved_proposal_route',
			'approve_and_execute_proposal_route',
			'/execute-approved-proposal',
			'/proposals/(?P<proposal_id>[A-Za-z0-9_-]+)/execute',
			'/proposals/(?P<proposal_id>[A-Za-z0-9_-]+)/approve-and-execute',
			'approved_proposal_execution_routes',
			'approved_proposal_execution',
			'unified_approve_and_execute',
			'core_approval_then_adapter_execution',
			'magick_ai_adapter_unified_action',
			'core_approved_commit_preflight_required',
			'wp_abilities_rest_after_core_preflight',
			'MAX_EXECUTION_ACTIONS',
			'execution_input_contract',
			'partial_success',
			'batch_write_actions',
			'normalize_execution_actions',
			'execute_normalized_action',
			'magick_ai_adapter_execute_ability_not_allowed',
			'magick_ai_adapter_execution_input_ambiguous',
			'magick_ai_adapter_write_action_invalid',
			'magick_ai_adapter_write_action_target_required',
			'magick_ai_adapter_write_actions_limit_exceeded',
			'magick_ai_adapter_write_action_commit_execution_not_allowed',
			'magick_ai_adapter_preflight_not_authorized',
			'magick_ai_adapter_core_execution_not_allowed',
			'magick_ai_adapter_proposal_rejected',
			'magick_ai_adapter_preflight_item_blocked',
			'magick_ai_adapter_preflight_correlation_required',
			'execute_core_approved_proposal',
			'get_core_proposal_data',
			'validate_execute_ability',
			'dispatch_upstream_with_runtime_context',
			'magick_ai_runtime_wp_ability_context',
			'sanitize_runtime_context',
			'approval_commit_authorized',
			'approval_context',
			'proposal_caller_context',
			"'term_id'",
			'plugin_conflict_input',
			'plugin_group_fields',
			'error_log_summary_fields',
			'workflow-recipes',
		'/workflow-recipe',
		"'media'",
		"'posts'",
		"'post-context'",
		"'users'",
		"'menu'",
		"'pages'",
		"'site-operations-dashboard'",
		'/proposals',
		'/proposals/from-plan',
		'create_proposals_from_plan',
		'list_proposals',
		'get_proposal',
		'approval_proxy_disabled',
		'/proposals/(?P<proposal_id>[A-Za-z0-9_-]+)/approve',
		'/proposals/(?P<proposal_id>[A-Za-z0-9_-]+)/reject',
		'/commit-preflight',
		"current_user_can( 'manage_options' )",
		'/magick-ai-core/v1/capabilities',
		'/magick-ai-core/v1/proposals',
		"caller_type' => 'openclaw_adapter'",
		"'via'         => 'magick-ai-adapter'",
		'/wp-abilities/v1/abilities/',
		'governance_mode',
		'direct_read',
		'proposal_required',
		'wp_abilities_rest',
		'adapter_after_core_preflight',
		'direct_read_plan_to_core_proposals',
		'plan_to_proposal',
		'core_proxy_execute',
		'commit_execution',
		'plan_fields_preserved',
		'batch_id',
		'issue_types',
		'attachment_ids',
		'post_ids',
		'write_actions',
		'manual_review',
		'skipped_destructive_candidates',
		'issue_counts',
		'action_count',
		'adapter_base_url',
		'help_url',
		'proposal_list_url',
		'proposal_detail_url',
		'read_shortcuts',
		'wordpress_rest_application_password',
		'proposal_status',
		'proposals:read',
		'approval_proxy_enabled',
		'approval_surface',
		'magick_ai_core_admin',
		'log_context',
		'wpai_request_log_context',
		'append_ai_request_log_context',
		'with_ai_request_log_context',
		'ai_request_log_context',
		'proposal_id',
		'correlation_id',
		'adapter_request_id',
		'adapter_route',
		'ai_provider',
		'ai_model',
		'governance_source',
		'magick_ai_core',
		'wp_ai_client_prompt',
		'qwen3.5:0.8b',
		'POST /ai-provider-log-correlation-smoke',
		'magick_ai_adapter',
		'proposal_status_routes',
		'plan_proposal_routes',
		'core_app_token_configured',
		'core_app_token_required_scopes',
		'GET /proposals',
		'GET /proposals/{proposal_id}',
			'POST /proposals/{proposal_id}/approve',
			'POST /proposals/{proposal_id}/reject',
			'magick_ai_adapter_approval_proxy_disabled',
			'unified_action_route',
			'approve-and-execute',
			'MAGICK_AI_ADAPTER_CORE_APP_TOKEN',
		'magick_ai_adapter_core_app_token',
		'x-magick-ai-core-app-token',
		'magick_ai_adapter_proposal_required',
		'magick-ai/site-info',
			'magick-ai-abilities/site-summary',
			'magick-ai-abilities/wp-diagnostics-summary',
			'magick-ai-abilities/wp-ops-diagnostics-detail',
			'magick-ai-abilities/list-workflow-recipes',
		'magick-ai-abilities/get-workflow-recipe',
		'magick-ai/list-posts',
		'magick-ai/get-post-context',
		'magick-ai/list-media',
		'magick-ai/list-users',
		'magick-ai/get-menu',
		'magick-ai/list-pages',
		'magick-ai/get-site-operations-dashboard',
		'magick-ai/build-content-inventory-fix-plan',
		'magick-ai/build-test-content-cleanup-plan',
		'magick-ai/build-media-inventory-fix-plan',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $controller, $required ), 'Controller contains required text: ' . $required );
}
maa_adapter_assert( false === strpos( $controller, '$allowed_execute_ability_ids' ), 'Controller derives execute allowlist from execution profiles.' );
maa_adapter_assert( false === strpos( $controller, 'include_log_tail' ), 'Adapter does not implement old include_log_tail compatibility.' );
maa_adapter_assert( false === strpos( $controller, 'include_error_log' ), 'Adapter does not use old include_error_log diagnostics input.' );
maa_adapter_assert( false === strpos( $controller, 'can_approve_proposals' ), 'Adapter does not call Core proposal approval permission path.' );
maa_adapter_assert( false === strpos( $controller, 'can_reject_proposals' ), 'Adapter does not call Core proposal rejection permission path.' );
maa_adapter_assert( false === strpos( $controller, 'approve_proposal' ), 'Adapter does not call Core proposal approval callback.' );
maa_adapter_assert( false === strpos( $controller, 'reject_proposal' ), 'Adapter does not call Core proposal rejection callback.' );
maa_adapter_assert( false === strpos( $controller, 'proposals:approve' ), 'Adapter does not request proposal approval scope.' );
maa_adapter_assert( false === strpos( $controller, 'proposals:reject' ), 'Adapter does not request proposal rejection scope.' );

$plugin = maa_adapter_read( $root . '/includes/Plugin.php' );
foreach (
	array(
		'admin_menu',
		'admin_post_magick_ai_adapter_create_openclaw_password',
		'register_admin_page',
		'handle_create_openclaw_password',
		'Admin\\Connection_Page',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $plugin, $required ), 'Plugin registers admin page text: ' . $required );
}

$connection_page = maa_adapter_read( $root . '/includes/Admin/Connection_Page.php' );
foreach (
	array(
		'Magick AI Adapter',
		'Adapter',
		'OpenClaw Handoff Created',
		'Create OpenClaw handoff',
		'add_submenu_page',
		'PARENT_MENU_SLUG',
		'WP_Application_Passwords::create_new_application_password',
		'Include LocalWP TLS setting',
		'This only changes copied client configuration',
		'data-maa-tab="connection"',
		'data-maa-tab="advanced"',
		'OpenClaw endpoint',
		'Adapter Base URL',
		'WordPress user',
		'Copy env',
		'Connection manifest',
		'openclaw_connection_manifest_text',
		'WorkBuddy setup',
		'Copy WorkBuddy setup',
		'workbuddy_handoff_text',
		'Magick AI Adapter WorkBuddy connection',
		'wordpress_application_password',
		'connection_id',
		'local-wordpress',
		'wordpress_application_password',
		'password_uuid',
		'Secret must be stored through OpenClaw credential store or dedicated secret field',
		'Diagnostics URLs',
		'Route catalog',
		'details class="maa-section"',
		'Proposal list',
		'Proposal detail',
		'Plan to proposals',
		'Commit preflight',
		'Approve and execute',
		'Approval disabled stub',
		'Reject disabled stub',
		'Example requests',
		'Handoff prompt',
		'Boundary',
		'MAGICK_AI_ADAPTER_APPLICATION_PASSWORD',
		'MAGICK_AI_ADAPTER_APPLICATION_PASSWORD=<store-in-openclaw-secret-vault>',
		'Copy this Application Password now.',
		'Paste it only into OpenClaw dedicated secret field',
		'GET /help',
		'GET /proposals/{proposal_id}',
		'approval_proxy_enabled=false',
		'approve-and-execute',
		'Current execution allowlist: magick-ai/trash-post, magick-ai/create-draft, magick-ai/update-post, magick-ai/set-post-seo-meta, magick-ai/set-post-slug, magick-ai/set-post-terms, magick-ai/delete-term, magick-ai/update-media-details, magick-ai/reply-comment, magick-ai/trash-comment, magick-ai/approve-comment',
		'Failure code handling',
		'magick_ai_adapter_preflight_item_blocked',
		'AI Request Logs context',
		'wpai_request_log_context',
		'log_context',
		'proposal_id',
		'correlation_id',
		'core_proxy_execute=false',
		'commit_execution=false',
		'<openclaw-secret-field-value>',
		'Key pair clients',
		'Device-paired clients',
		'key_pairs_url',
		'REVOKE_KEY_ACTION',
		'Connection approved.',
		'Return to the terminal or local AI client',
		'private key was never sent to WordPress',
		'Connection rejected.',
		'PAIR_MENU_SLUG',
		'result_status',
		'/connection/manifest',
		'/connection/key-pairs',
		'Controller::read_shortcuts',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $connection_page, $required ), 'Connection page contains required text: ' . $required );
}
$env_password_key       = 'MAGICK_AI_ADAPTER_APPLICATION_PASSWORD=';
$php_password_variable  = '$password';
maa_adapter_assert( false === strpos( $connection_page, $env_password_key . "' . " . $php_password_variable ), 'Connection page env text does not interpolate the real secret.' );
maa_adapter_assert( false === strpos( $connection_page, '$this->openclaw_env_text( $username, $password,' ), 'Connection page does not pass the real Application Password into env text.' );
maa_adapter_assert( false === strpos( $connection_page, '$this->openclaw_created_handoff_text( $username, $password,' ), 'Connection page does not pass the real secret into copied handoff.' );
maa_adapter_assert( false === strpos( $connection_page, '$this->workbuddy_handoff_text( $username, $password,' ), 'Connection page does not pass the real secret into WorkBuddy setup.' );
maa_adapter_assert( false !== strpos( $connection_page, 'openclaw_connection_manifest_text( string $username, string $password_uuid )' ), 'Connection manifest receives only username and password UUID.' );
maa_adapter_assert( false !== strpos( $connection_page, 'openclaw_created_handoff_text( string $username, string $password_uuid, bool $include_local_tls )' ), 'Created handoff text receives only username, password UUID, and TLS placeholder flag.' );
maa_adapter_assert( false !== strpos( $connection_page, 'workbuddy_handoff_text( string $username, string $password_uuid, bool $include_local_tls )' ), 'WorkBuddy setup text receives only username, password UUID, and TLS placeholder flag.' );
maa_adapter_assert( false !== strpos( $connection_page, "const MENU_SLUG        = 'magick-ai-adapter';" ), 'Connection page uses the canonical Adapter admin slug.' );
maa_adapter_assert( false !== strpos( $connection_page, "__( 'Magick AI Adapter', 'magick-ai-adapter' ),\n\t\t\t__( 'Adapter', 'magick-ai-adapter' )," ), 'Connection page registers the requested page and menu titles.' );
maa_adapter_assert( false === strpos( $connection_page, 'magick-ai-adapter-openclaw' ), 'Connection page does not use the old OpenClaw-specific admin slug.' );
maa_adapter_assert( false !== strpos( $connection_page, "'magick-ai-cloud-addon'" ), 'Connection page overview links to the canonical Cloud Addon slug.' );
maa_adapter_assert( false !== strpos( $connection_page, "__( 'Cloud Addon', 'magick-ai-adapter' )" ), 'Connection page overview labels the Cloud Addon surface.' );

$admin_surface_standard = maa_adapter_read( $root . '/docs/admin-surface-standard.md' );
foreach (
	array(
		'OpenClaw connection surface',
		'Create OpenClaw handoff',
		'read shortcut route catalog',
		'Core proposal approval tables',
		'ability definitions',
		'Cloud Base URL/API key',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $admin_surface_standard, $required ), 'Admin surface standard documents Adapter page boundary: ' . $required );
}

$readme = maa_adapter_read( $root . '/README.md' );
foreach (
	array(
		'thin OpenClaw channel plugin',
		'read Magick AI Core capability guidance',
		'run approved direct-read abilities through WordPress Abilities API',
		'create Core proposals',
		'does not define abilities',
		'execute final write mutations',
		'Magick AI -> Adapter',
		'docs/openclaw-quickstart.md',
		'docs/openclaw-consumer-acceptance.md',
		'docs/openclaw-batch-execution-policy.md',
		'input.write_actions[]',
		'execution profile registry',
		'Capability discovery may show more proposal-required abilities',
		'$outputs.create-draft.post_id',
		'Create OpenClaw handoff',
		'only its hash',
			'Application Password secret-field',
			'non-secret connection manifest',
			'copyable WorkBuddy setup block',
			'key-pair device pairing MVP',
			'docs/keypair-device-pairing-contract.md',
			'tools/keypair-device-pairing.mjs',
			'tools/keypair-adapter-request.mjs',
			'Public Key Device Pairing',
			'OpenClaw only connects to Adapter',
			'productized OpenClaw user action',
			'GET /wp-json/magick-ai-adapter/v1/help',
		'POST /wp-json/magick-ai-adapter/v1/ai-provider-log-correlation-smoke',
			'GET /wp-json/magick-ai-adapter/v1/site-summary',
			'GET /wp-json/magick-ai-adapter/v1/active-plugins-detail',
			'GET /wp-json/magick-ai-adapter/v1/plugin-conflict-diagnostics',
			'GET /wp-json/magick-ai-adapter/v1/recent-error-log',
			'GET /wp-json/magick-ai-adapter/v1/recent-error-log-tail',
			'GET /wp-json/magick-ai-adapter/v1/current-user-permissions',
			'GET /wp-json/magick-ai-adapter/v1/php-extensions',
			'GET /wp-json/magick-ai-adapter/v1/object-cache-status',
			'GET /wp-json/magick-ai-adapter/v1/database-info',
			'GET /wp-json/magick-ai-adapter/v1/rewrite-rules-status',
			'GET /wp-json/magick-ai-adapter/v1/cron-events-detail',
			'GET /wp-json/magick-ai-adapter/v1/server-info',
			'GET /wp-json/magick-ai-adapter/v1/integrations-status',
			'GET /wp-json/magick-ai-adapter/v1/seo-summary',
			'GET /wp-json/magick-ai-adapter/v1/security-summary',
			'GET /wp-json/magick-ai-adapter/v1/performance-summary',
			'GET /wp-json/magick-ai-adapter/v1/posts',
			'GET /wp-json/magick-ai-adapter/v1/post-context',
			'GET /wp-json/magick-ai-adapter/v1/users',
			'GET /wp-json/magick-ai-adapter/v1/menu',
			'GET /wp-json/magick-ai-adapter/v1/media',
			'include_log_contents',
			'include_inactive_plugins',
			'max_plugins_per_group',
			'tail_lines',
			'since_minutes',
			'not explicitly requested',
			'error_log.tail_entries',
			'error_log.summary',
			'fatal_count',
			'deprecated_count',
			'summary_source',
			'error_log.summary.by_severity',
		'GET /wp-json/magick-ai-adapter/v1/site-operations-dashboard',
		'GET /wp-json/magick-ai-adapter/v1/proposals',
		'GET /wp-json/magick-ai-adapter/v1/proposals/{proposal_id}',
		'POST /wp-json/magick-ai-adapter/v1/proposals/from-plan',
		'POST /wp-json/magick-ai-adapter/v1/execute-approved-proposal',
		'POST /wp-json/magick-ai-adapter/v1/proposals/{proposal_id}/execute',
		'POST /wp-json/magick-ai-adapter/v1/proposals/{proposal_id}/approve-and-execute',
		'POST /wp-json/magick-ai-adapter/v1/proposals/{proposal_id}/approve',
		'POST /wp-json/magick-ai-adapter/v1/proposals/{proposal_id}/reject',
		'approved proposal execution',
		'approve-and-execute',
		'magick-ai/trash-post',
		'magick-ai/create-draft',
		'magick-ai/update-post',
		'magick-ai/set-post-seo-meta',
		'magick-ai/set-post-slug',
		'magick-ai/set-post-terms',
		'magick-ai/delete-term',
		'magick-ai/update-media-details',
		'magick-ai/reply-comment',
		'magick-ai/trash-comment',
		'magick-ai/approve-comment',
		'MAGICK_AI_ADAPTER_CORE_APP_TOKEN',
		'magick_ai_adapter_core_app_token',
		'magick_ai_adapter_approval_proxy_disabled',
		'approval_proxy_enabled=false',
		'approval_surface=magick_ai_core_admin',
		'POST /wp-json/magick-ai-adapter/v1/run-read-ability',
		'proposals:read',
		'audit_timeline',
		'Core Governance Audit is the governance log',
			'AI Request Logs are the provider request log',
			'adapter_request_id',
			'adapter_route',
			'explicit `ai_provider`',
			'explicit `ai_model`',
			'governance_source=magick-ai-core',
		'magick_ai_core.proposal_id',
		'magick_ai_core.correlation_id',
		'governance_mode=direct_read',
		'governance_mode=proposal_required',
		'magick-ai/build-content-inventory-fix-plan',
		'magick-ai/build-test-content-cleanup-plan',
		'magick-ai/build-media-inventory-fix-plan',
		'skipped_destructive_candidates',
		'write_actions',
		'Plan-to-proposal flow',
		'POST /magick-ai-core/v1/proposals/from-plan',
		'core_proxy_execute=false',
		'commit_execution=false',
		'composer plugin-check:release',
		'composer package:release',
		'.distignore',
		'Do not delete',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $readme, $required ), 'README contains required text: ' . $required );
}

$keypair_tool = maa_adapter_read( $root . '/tools/keypair-device-pairing.mjs' );
foreach (
	array(
		'generateKeyPairSync',
		'ed25519',
		'connect/device/start',
		'connect/device/poll',
		'X-Magick-Key-Id',
		'X-Magick-Signature',
		'Authorization',
		'Magick-Signature',
		'MAGICK-AI-ADAPTER-V1',
		'insecure-local-tls',
		'no-open',
		'openApprovalUrl',
		'isRetryableNetworkError',
		'Transient polling error',
		'Health check failed after pairing',
		'Object.keys(value).length === 0',
		'private_key_jwk',
		'keypair-profiles',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $keypair_tool, $required ), 'Keypair pairing tool contains expected behavior: ' . $required );
}
maa_adapter_assert( false === strpos( $keypair_tool, 'console.log(private' ), 'Keypair tool does not print private key material.' );

$keypair_request_tool = maa_adapter_read( $root . '/tools/keypair-adapter-request.mjs' );
foreach (
	array(
		'createPrivateKey',
		'private_key_jwk',
		'keypair-profiles',
		'isSafeAdapterRoute',
		'--body-file',
		'--query',
		'--query-string',
		'Magick-Signature',
		'Authorization',
		'X-Magick-Signature',
		'MAGICK-AI-ADAPTER-V1',
		'Object.keys(value).length === 0',
		'wrapper_failed',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $keypair_request_tool, $required ), 'Keypair request wrapper contains expected behavior: ' . $required );
}
maa_adapter_assert( false === strpos( $keypair_request_tool, 'console.log(profile' ), 'Keypair request wrapper does not print profile data.' );
maa_adapter_assert( false === strpos( $keypair_request_tool, 'console.log(headers' ), 'Keypair request wrapper does not print signature headers.' );

$wporg_readme = maa_adapter_read( $root . '/readme.txt' );
foreach (
	array(
		'=== Magick AI Adapter ===',
		'Requires at least: 7.0',
		'Tested up to: 7.0',
		'Requires PHP: 8.0',
		'Stable tag: 0.1.0',
		'License: GPL-2.0-or-later',
		'Magick AI Core remains the governance backend',
		'magick-ai/trash-post',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $wporg_readme, $required ), 'readme.txt contains required text: ' . $required );
}

$composer = maa_adapter_read( $root . '/composer.json' );
foreach (
	array(
		'"license": "GPL-2.0-or-later"',
		'"package:release"',
		'"plugin-check:release"',
		'--exclude-directories=tests,.git,vendor,node_modules,build,sj',
		'--exclude-files=.gitignore,.distignore,AGENTS.md,composer.json',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $composer, $required ), 'composer.json contains required text: ' . $required );
}

$distignore = maa_adapter_read( $root . '/.distignore' );
foreach (
	array(
		'.git',
		'.distignore',
		'.gitignore',
		'AGENTS.md',
		'build',
		'composer.json',
		'tests',
		'tools',
		'vendor',
		'node_modules',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $distignore, $required ), '.distignore excludes development artifact: ' . $required );
}

$quickstart = maa_adapter_read( $root . '/docs/openclaw-quickstart.md' );
foreach (
	array(
		'OpenClaw Quickstart',
		'OpenClaw only connects to Adapter',
		'https://magick-ai.local',
		'WordPress administrator username: `1`',
		'WordPress administrator password: `1`',
		'Application Password',
		'Create OpenClaw handoff',
		'GET /health',
		'GET /help',
		'GET /capabilities',
		'Public Key Device Pairing',
		'tools/keypair-device-pairing.mjs',
		'connect/device/start',
		'POST /proposals/from-plan',
		'/proposals?limit=10',
		'/proposals/PROPOSAL_ID',
		'proposals:read',
		'audit_timeline',
		'MAGICK_AI_ADAPTER_CORE_APP_TOKEN',
			'magick_ai_adapter_core_app_token',
			'magick_ai_adapter_approval_proxy_disabled',
			'approve-and-execute',
			'magick_ai_adapter_execute_ability_not_allowed',
			'approval_proxy_enabled=false',
		'approval_surface=magick_ai_core_admin',
		'log_context',
		'wpai_request_log_context',
		'proposal_id',
		'correlation_id',
		'adapter_request_id',
		'adapter_route',
		'ai_provider',
		'ai_model',
		'qwen3.5:0.8b',
		'/ai-provider-log-correlation-smoke',
		'Core Governance Audit is the governance log',
		'AI Request Logs are the provider request log',
			'/site-info',
			'/active-plugins-detail',
			'/plugin-conflict-diagnostics',
			'/recent-error-log',
			'/recent-error-log-tail',
			'/current-user-permissions',
			'/database-info',
			'/posts?author_id=1',
			'/terms?taxonomy=category&include_sample_posts=1',
			'/menu?location=primary',
		'/media?per_page=1',
		'/content-inventory-fix-plan?per_page=1&max_actions=1',
		'magick-ai/build-content-inventory-fix-plan',
		'write_actions',
		'not as completed writes',
		'/pages?per_page=1',
		'wp-diagnostics-summary` to decide whether plugin details',
		'include_inactive_plugins=true',
		'Default inactive plugin rows are not missing',
		'error_log.summary.fatal_count',
		'not explicitly requested',
		'contents_included=true',
		'error_log.summary.by_severity',
			'Proposal-Required Write Flow',
			'core_proxy_execute=false',
			'commit_execution=false',
			'execution_mode=batch_write_actions',
			'outside that execution allowlist',
		) as $required
) {
	maa_adapter_assert( false !== strpos( $quickstart, $required ), 'Quickstart contains required text: ' . $required );
}

$contract = maa_adapter_read( $root . '/docs/openclaw-adapter-contract.md' );
foreach (
	array(
		'initial productization contract',
		'magick-ai-abilities',
		'magick-ai-core',
		'core_proxy_execute',
		'commit_execution',
		'Magick AI -> Adapter',
		'Application Password Handoff',
		'Proposal Status Read Proxy',
			'Approval Disabled Stub Contract',
			'OpenClaw only connects to Adapter',
			'unified_action_route',
			'approve-and-execute',
			'show the raw password',
		'It must not store',
		'raw secrets in adapter options, manifest JSON, handoff text',
		'username `1` and password `1`',
		'Proposal-Required Write Flow',
		'GET /wp-json/magick-ai-adapter/v1/help',
		'GET /wp-json/magick-ai-adapter/v1/proposals',
		'GET /wp-json/magick-ai-adapter/v1/proposals/{proposal_id}',
		'POST /wp-json/magick-ai-adapter/v1/proposals/from-plan',
		'POST /wp-json/magick-ai-adapter/v1/proposals/{proposal_id}/execute',
		'POST /wp-json/magick-ai-adapter/v1/proposals/{proposal_id}/approve-and-execute',
		'GET /wp-json/magick-ai-adapter/v1/recent-error-log-tail',
		'GET /wp-json/magick-ai-adapter/v1/plugin-conflict-diagnostics',
		'GET /wp-json/magick-ai-adapter/v1/posts',
		'GET /wp-json/magick-ai-adapter/v1/post-context',
		'GET /wp-json/magick-ai-adapter/v1/users',
		'GET /wp-json/magick-ai-adapter/v1/menu',
		'POST /wp-json/magick-ai-adapter/v1/proposals/{proposal_id}/approve',
		'POST /wp-json/magick-ai-adapter/v1/proposals/{proposal_id}/reject',
		'magick_ai_adapter_approval_proxy_disabled',
		'approval_proxy_enabled=false',
		'approval_surface=magick_ai_core_admin',
		'proposals:read',
		'audit_timeline',
		'AI Request Logs',
		'wp-diagnostics-summary` is only a quick overview',
		'POST /wp-json/magick-ai-adapter/v1/ai-provider-log-correlation-smoke',
		'Core Governance Audit is the governance log',
		'AI Request Logs are the provider request log',
		'adapter_request_id',
		'adapter_route',
		'ai_provider',
		'ai_model',
		'qwen3.5:0.8b',
		'governance_source=magick-ai-core',
		'magick_ai_core.proposal_id',
		'magick_ai_core.correlation_id',
		'include_log_contents',
		'include_inactive_plugins',
		'max_plugins_per_group',
		'tail_lines',
		'since_minutes',
		'not explicitly requested',
		'Inactive plugin rows are not requested by default',
		'fatal_count',
		'warning_count',
		'deprecated_count',
		'notice_count',
		'summary_source',
		'error_log.tail_entries',
		'error_log.summary.by_severity',
		'include_log_tail',
		'Magick AI runtime, MCP, or cloud status',
		'plugin_file',
		'network_active',
		'dependency_count',
		'magick_ai_permissions',
		'severity_filter',
		'since_minutes',
		'author_id',
		'include_sample_posts',
		'author_profile',
		'attached_to',
		'magick-ai/get-menu',
		'wpai_request_log_context',
		'log_context',
		'proposal_id',
		'correlation_id',
		'MAGICK_AI_ADAPTER_CORE_APP_TOKEN',
		'magick_ai_adapter_core_app_token',
		'Read-Only Planning Contract',
		'magick-ai/build-content-inventory-fix-plan',
		'magick-ai/build-test-content-cleanup-plan',
		'magick-ai/build-media-inventory-fix-plan',
		'skipped_destructive_candidates',
		'magick-ai/delete-media-permanently',
		'Approved Proposal Execution Contract',
		'Unified Approve And Execute Contract',
		'openclaw-batch-execution-policy.md',
		'batch containing any non-allowlisted action fails',
		'magick-ai/trash-post',
		'magick-ai/create-draft',
		'magick-ai/update-post',
		'magick-ai/set-post-seo-meta',
		'magick-ai/set-post-slug',
		'magick-ai/set-post-terms',
		'magick-ai/delete-term',
		'magick-ai/update-media-details',
		'magick-ai/reply-comment',
		'magick-ai/trash-comment',
		'magick-ai/approve-comment',
		'execution profile registry',
		'capability discovery',
		'POST /proposals',
		'undeclared input fields',
		'invalid enum values',
		'`magick-ai/update-post` does not accept `status`',
		'$outputs.<prior_action_id>.<field>',
		'cannot be embedded into larger strings',
		'POST /wp-json/magick-ai-core/v1/proposals/from-plan',
		'The read path does not execute abilities marked `proposal_required`.',
		'The adapter does not store proposal governance state.',
		'explicit unified approve-and-execute action',
		'All routes require `manage_options`',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $contract, $required ), 'Adapter contract contains required text: ' . $required );
}

$acceptance = maa_adapter_read( $root . '/docs/openclaw-consumer-acceptance.md' );
foreach (
	array(
		'OpenClaw Consumer Acceptance',
		'OpenClaw must not connect directly to Magick AI Core for productized use.',
		'GET /health',
		'GET /help',
		'GET /capabilities',
		'GET /proposals',
		'GET /proposals/{proposal_id}',
		'POST /proposals',
		'POST /proposals/from-plan',
		'POST /proposals/{proposal_id}/commit-preflight',
		'POST /proposals/{proposal_id}/execute',
		'POST /proposals/{proposal_id}/approve-and-execute',
		'execution_mode=batch_write_actions',
		'magick_ai_adapter_write_action_invalid',
		'approved proposal execution',
		'approve-and-execute',
		'magick-ai/trash-post',
		'magick-ai/create-draft',
		'magick-ai/update-post',
		'magick-ai/set-post-seo-meta',
		'magick-ai/set-post-slug',
		'magick-ai/set-post-terms',
		'magick-ai/delete-term',
		'magick-ai/update-media-details',
		'magick-ai/reply-comment',
		'magick-ai/trash-comment',
		'magick-ai/approve-comment',
		'active-plugins-detail',
		'plugin-conflict-diagnostics',
		'current-user-permissions',
		'database-info',
		'recent-error-log-tail',
		'wp-ops-diagnostics-detail',
		'include_log_contents=false',
		'include_inactive_plugins=false',
		'include_inactive_plugins=true',
		'not explicitly',
		'error_log.summary.fatal_count',
		'error_log.tail_entries',
		'error_log.summary.by_severity',
		'Core Governance Audit',
		'AI Request Logs',
		'POST /ai-provider-log-correlation-smoke',
		'configured text',
		'generation provider/model',
		'explicit `ai_provider`',
		'`ai_model` sent to the provider smoke',
		'adapter_request_id',
		'governance_source=magick-ai-core',
		'provider request log',
		'magick_ai_adapter_approval_proxy_disabled',
		'magick-ai/build-content-inventory-fix-plan',
		'magick-ai/build-test-content-cleanup-plan',
		'magick-ai/build-media-inventory-fix-plan',
		'plan-to-proposal forwarding',
		'skipped_destructive_candidates',
		'write_actions',
		'commit_execution=false',
		'no new runtime ownership',
		'composer plugin-check:release',
		'composer package:release',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $acceptance, $required ), 'OpenClaw acceptance doc contains required text: ' . $required );
}

$agents = maa_adapter_read( $root . '/AGENTS.md' );
foreach (
	array(
		'thin OpenClaw channel layer',
		'does not own',
		'magick-ai-abilities',
		'magick-ai-core',
		'core_proxy_execute=false',
		'commit_execution=false',
		'composer plugin-check:release',
		'composer package:release',
		'.distignore',
	) as $required
) {
maa_adapter_assert( false !== strpos( $agents, $required ), 'AGENTS.md contains required text: ' . $required );
}

$smoke_sh = maa_adapter_read( $root . '/tests/smoke-wp.sh' );
foreach (
	array(
		'wp-content/plugins/magick-ai-adapter',
		'wp plugin activate magick-ai-adapter',
		'eval-file "$ROOT_DIR/tests/smoke-wp.php"',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $smoke_sh, $required ), 'Smoke shell contains required text: ' . $required );
}

$smoke_wp = maa_adapter_read( $root . '/tests/smoke-wp.php' );
foreach (
	array(
		'/magick-ai-adapter/v1/health',
		'/magick-ai-adapter/v1/help',
		'/magick-ai-adapter/v1/capabilities',
			'/magick-ai-adapter/v1/site-summary',
			'/magick-ai-adapter/v1/wp-diagnostics-summary',
			'/magick-ai-adapter/v1/active-plugins-detail',
			'/magick-ai-adapter/v1/plugin-conflict-diagnostics',
			'/magick-ai-adapter/v1/recent-error-log',
			'/magick-ai-adapter/v1/recent-error-log-tail',
			'/magick-ai-adapter/v1/current-user-permissions',
			'/magick-ai-adapter/v1/database-info',
			'/magick-ai-adapter/v1/cron-events-detail',
			'/magick-ai-adapter/v1/workflow-recipes',
		'/magick-ai-adapter/v1/workflow-recipe',
		'/magick-ai-adapter/v1/proposals',
		'/magick-ai-adapter/v1/proposals/from-plan',
		'adapter plan-to-proposal rejects invalid profiled action input before Core forwarding',
		'invalid-update-post-status',
		'adapter plan action input rejection carries field',
		'adapter from-plan output references create one batch proposal',
		'adapter from-plan output-reference batch approve-and-execute succeeds',
		'adapter plan-to-proposal rejects duplicate action ids before Core forwarding',
		'adapter plan-to-proposal rejects embedded output reference tokens before Core forwarding',
		'adapter batch approve-and-execute rejects embedded output reference tokens before execution',
		'/execute',
		'/magick-ai-adapter/v1/execute-approved-proposal',
		'/approve-and-execute',
		'/magick-ai-adapter/v1/ai-provider-log-correlation-smoke',
		'/ai/v1/logs',
		'/magick-ai-core/v1/audit',
			'magick-ai-abilities/site-summary',
			'magick-ai-abilities/wp-diagnostics-summary',
			'magick-ai-abilities/wp-ops-diagnostics-detail',
			'magick-ai-abilities/list-workflow-recipes',
		'magick-ai-abilities/get-workflow-recipe',
		'magick-ai/build-content-inventory-fix-plan',
		'magick-ai/build-test-content-cleanup-plan',
		'magick-ai/build-media-inventory-fix-plan',
		'magick-ai/list-posts',
		'magick-ai/get-post-context',
		'magick-ai/list-users',
		'magick-ai/get-menu',
		'include_log_contents',
		'include_inactive_plugins',
		'max_plugins_per_group',
		'tail_entries',
		'by_severity',
		'plugin conflict diagnostic requests inactive plugin rows',
		'default error log diagnostic exposes severity summary without log contents',
		'adapter_request_id',
		'adapter_route',
		'ai_provider',
		'ai_model',
		'governance_source',
		'magick_ai_core',
		'qwen3.5:0.8b',
		'adapter refuses direct execution for proposal-required ability',
		'adapter refuses direct execution for destructive ability',
		'adapter health exposes approved proposal execution route',
		'adapter health exposes approve-and-execute route',
		'adapter health exposes trash-post execute allowlist',
		'adapter help exposes execute-approved-proposal route',
		'adapter help exposes proposal execute route',
		'adapter help exposes proposal approve-and-execute route',
		'adapter smoke created trash-post fixture',
		'adapter creates trash-post proposal for approved execution smoke',
		'adapter trash-post proposal starts pending',
		'adapter execute refuses pending proposal',
		'adapter pending execute leaves post published',
		'Core admin REST approval succeeds for adapter trash execution smoke',
		'adapter executes approved trash-post proposal',
		'adapter execute response carries proposal id',
		'adapter execute response carries ability id',
		'adapter execute response carries correlation id',
		'adapter execute response carries adapter request id',
		'adapter execute response carries approval context',
		'adapter execute response preserves commit_execution=false',
		'adapter execute trashes post',
		'adapter execute returns non-dry-run ability result',
		'adapter approved execution moves post to trash',
		'adapter creates trash-post proposal for approve-and-execute smoke',
		'adapter approve-and-execute succeeds for pending trash-post proposal',
		'adapter approve-and-execute response carries proposal id',
		'adapter approve-and-execute response carries ability id',
		'adapter approve-and-execute response carries post id',
		'adapter approve-and-execute records pending status before approval',
		'adapter approve-and-execute auto approves pending proposal through Core',
		'adapter approve-and-execute response carries correlation id',
		'adapter approve-and-execute preserves Core commit_execution=false',
		'adapter approve-and-execute records post status before execution',
		'adapter approve-and-execute records post status after execution',
		'adapter approve-and-execute execution result succeeds',
		'adapter approve-and-execute moves pending proposal post to trash',
		'adapter creates write_actions batch proposal for approve-and-execute smoke',
		'adapter batch approve-and-execute succeeds for allowlisted write_actions',
		'adapter batch approve-and-execute reports batch execution mode',
		'adapter batch approve-and-execute returns per-action results',
		'adapter creates output-reference write_actions batch proposal',
		'adapter batch approve-and-execute succeeds with output references',
		'adapter output-reference batch updates the created draft',
		'adapter output-reference batch leaves created draft trashed',
		'adapter batch approve-and-execute rejects non-allowlisted write_action',
		'adapter bad batch does not execute allowed action before failing closed',
		'adapter approve-and-execute succeeds for already approved proposal',
		'adapter approve-and-execute records approved status before execution',
		'adapter approve-and-execute skips approve for already approved proposal',
		'adapter approve-and-execute moves already approved post to trash',
		'adapter approve-and-execute rejects rejected proposal',
		'adapter approve-and-execute does not execute rejected proposal',
		'adapter approve-and-execute returns preflight failure',
		'adapter approve-and-execute does not execute preflight-blocked proposal',
		'adapter proposal create rejects update-post without update fields',
		'adapter proposal create rejects update-post status input',
		'adapter update-post status rejection uses schema field error code',
		'adapter creates set-post-seo-meta proposal for approve-and-execute smoke',
		'adapter proposal create rejects set-post-seo-meta without SEO fields',
		'adapter creates set-post-slug proposal for approve-and-execute smoke',
		'adapter proposal create rejects set-post-slug without valid slug',
		'adapter proposal create rejects set-post-terms without terms',
		'adapter proposal create rejects set-post-terms create_missing',
		'adapter creates delete-term proposal for approve-and-execute smoke',
		'adapter approve-and-execute succeeds for pending delete-term proposal',
		'adapter proposal create rejects delete-term without term_id',
		'adapter proposal create rejects delete-term invalid taxonomy',
		'adapter creates update-media-details proposal for approve-and-execute smoke',
		'adapter proposal create rejects update-media-details without detail fields',
		'adapter proposal create rejects reply-comment without content',
		'adapter creates trash-comment proposal for approve-and-execute smoke',
		'adapter proposal create rejects trash-comment without comment_id',
		'adapter proposal create rejects approve-comment without comment_id',
		'adapter approve-and-execute rejects non-allowlisted ability',
		'adapter capabilities expose content inventory fix plan through Core',
		'adapter capabilities expose test content cleanup plan through Core',
		'adapter capabilities expose media inventory fix plan through Core',
		'adapter plan read preserves write_actions',
		'adapter plan read preserves preview',
		'adapter plan read preserves commit_execution=false',
		'adapter media plan preserves skipped destructive candidates field',
		'adapter media plan does not promote skipped deletes into write actions by default',
		'adapter media plan shortcut treats include_delete_candidates=false as false',
		'adapter forwards plan-to-proposal route to Core',
		'adapter rejects unallowed plan-to-proposal ability before Core forwarding',
		'adapter plan proposal caller carries adapter request id',
		'adapter e2e media plan creates Core proposal',
		'adapter e2e plan proposal detail preserves source plan preview',
		'adapter e2e plan proposal detail preserves manual review rows',
		'adapter e2e plan proposal detail preserves skipped destructive candidates',
		'adapter e2e media plan keeps delete-media-permanently out of created proposals by default',
		'adapter plan-to-proposal response preserves proposal list state',
		'adapter help exposes proposal list route',
		'adapter help exposes proposal detail route',
		'adapter help keeps approval proxy disabled',
		'adapter help keeps rejection proxy disabled',
		'adapter health exposes Core app token configured state without token value',
		'adapter help exposes Core app token configured state without token value',
		'adapter returns created proposal in Core proposal list',
		'adapter returns proposal detail through Core',
		'adapter proposal detail preserves audit timeline',
		'adapter read response exposes AI request log context',
		'adapter read log context carries proposal id',
			'adapter read log context carries correlation id',
			'adapter active plugins shortcut uses ops diagnostics detail',
			'adapter runs active plugins diagnostic shortcut through ops detail',
			'adapter runs current user permissions diagnostic shortcut through ops detail',
			'adapter runs explicit error log tail diagnostic through ops detail',
			'default error log diagnostic does not include log contents',
			'explicit error log tail diagnostic exposes redacted tail entries',
			'adapter runs database diagnostic shortcut',
			'adapter runs cron events diagnostic shortcut',
		'adapter approval stub returns disabled response',
			'adapter rejection stub returns disabled response',
			'adapter approval stub does not change Core proposal status',
			'adapter rejection stub does not change Core proposal status',
			'maa_adapter_smoke_text_generation_model',
			'AI provider smoke found a configured text generation model',
			'adapter provider smoke succeeds with configured text model',
			'adapter provider smoke context carries selected provider',
			'adapter provider smoke context carries selected model',
			'AI Request Logs context contains proposal id',
		'AI Request Logs context contains correlation id',
		'AI Request Logs context contains explicit provider even if provider column is blank',
		'AI Request Logs context contains explicit model even if provider column is blank',
		'Core Governance Audit filters by the same provider smoke correlation id',
		'adapter status smoke cleaned created proposal records',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $smoke_wp, $required ), 'WordPress smoke contains required text: ' . $required );
}

$batch_policy = maa_adapter_read( $root . '/docs/openclaw-batch-execution-policy.md' );
foreach (
	array(
		'OpenClaw Batch Execution Policy',
		'Status: accepted',
		'target_ability_id=magick-ai/trash-post',
		'target_ability_id=magick-ai/set-post-seo-meta',
		'target_ability_id=magick-ai/update-post',
		'target_ability_id=magick-ai/set-post-slug',
		'target_ability_id=magick-ai/set-post-terms',
		'target_ability_id=magick-ai/delete-term',
		'target_ability_id=magick-ai/update-media-details',
		'target_ability_id=magick-ai/reply-comment',
		'target_ability_id=magick-ai/trash-comment',
		'target_ability_id=magick-ai/approve-comment',
		'Execution Profile Registry',
		'Capability discovery is not enough to execute a write ability',
		'Adapter validates proposal input at `POST /proposals`',
		'POST /proposals/from-plan',
		'magick_ai_adapter_plan_action_input_invalid',
		'$outputs.<prior_action_id>.<field>',
		'invalid enum values',
		'$outputs.<prior_action_id>.<field>',
		'cannot point forward',
		'cannot be embedded into larger strings',
		'fail closed',
		'Maximum batch size is 50 actions',
		'Partial success is not a normal success mode',
		'execution_mode=batch_write_actions',
		'expand the Adapter execution allowlist',
		'turn disabled approve/reject stubs into real proxies',
	) as $required
) {
	maa_adapter_assert( false !== strpos( $batch_policy, $required ), 'Batch execution policy contains required text: ' . $required );
}

echo "Static contracts: ok\n";
